jenkins-infra/azure

.gitignore, Makefile, plans/remote-state.tf
See [INFRA-996](https://issues.jenkins-ci.org/browse/INFRA-996)
=> Enable Terraform remote state with Azure Blob storage

scripts/az
=> Add a handy script for running the latest azure-cli at all times

Makefile, plans/releases-storage.tf, plans/remote-state.tf, plans/variables.tf, plans/vnets-nsg.tf, plans/vnets.tf
This series of changes resolves [INFRA-995](https://issues.jenkins-ci.org/browse/INFRA-995)
See also [IEP-2](https://github.com/jenkins-infra/iep/tree/master/iep-002)
This is ready for review, but not quite ready for merge. First I want to ensure (manually) that resources provisioned (such as VMs) in these Virtual Networks behave as I expect them to.
=> Provision Virtual Networks for Development, Public and Private Production

scripts/az, scripts/purge-pr-resources
Also updating the purge-pr-resources script to reference the `az` script in our
repo
=> The azure-cli-python container deleted some tags which were denoted by image ID

plans/reports.tf
=> Add an Azure storage blob container for reports

plans/repo_proxy.tf
Deploy shared disk storage to store proxy cache files for repo.azure.jenkins-ci.org
=> Shared Disk storage for repo.azure.jenkins-ci.org

Makefile
Check that python2 is used for the Makefile
=> Add python2 check

.gitignore, Jenkinsfile, Makefile, backend.tf, plans/backend.tf, plans/remote-state.tf, scripts/terraform
! This PR upgrade terraform to version 0.9 and require manual steps to migrate remote state to backend as explain [here](https://www.terraform.io/docs/backends/legacy-0-8.html)
Remark: Manual step is done in stage('Pull remote') which should be remove once the backend is upgraded
=> [WIP] [INFRA-1288] Upgrade terraform to 0.9.9

Jenkinsfile
Remove onetime backend upgrade operations
Require: following key/value on the remote terraform state 
terraform_version: "0.9.9"
=> Jenkinsfile: Remove onetime backend upgrade operations

plans/backups.tf
See INFRA-1148
See also jenkins-infra/jenkins-infra#764
=> Add some Azure resources for Azure-hosted backups

plans/reports.tf
I'm pretty sure I made this change manually in production like a dumby.
=> Codify the custom domain for the reports group.

plans/vnets-nsg.tf
Forgot about these NSGs in my previous changes for INFRA-1274
=> Allow inbound SSH in the DMZ tier.

scripts/purge-pr-resources
should the string read "Proceed" ?
Hope this helps?
=> Propose small spelling correction to script string

plans/provider.tf
This new provider version should include a fix for following issues:
https://issues.jenkins-ci.org/browse/INFRA-1467
https://github.com/terraform-providers/terraform-provider-azurerm/issues/743
=> [INFRA-1467] Bump Azurerm provider version to 1.1.0

plans/uplink.tf, plans/variables.tf
Deploy a postgresql database asked by @daniel-beck
=> Add uplink Database

plans/confluence.tf
Align with a manual change done on confluence database
=> Disable SSL enforcement on confluence

plans/uplink.tf
This PR align the jenkins-infra/azure repository with a manual change that was introduced because of INFRA-1854
=> [INFRA-1854] Bump uplink database size

plans/dns_jenkinsio.tf, plans/machine_certci.tf, plans/machine_certsci.tf
This PR provision a machine in order to host a private jenkins instance.
=> [INFRA-1912] Provision certs.ci.jenkins.io machine

plans/dns_jenkinsci.tf
Haven't tested this on my local machine since some local keys are all out of
date
=> Attempt to add the new jenkins-ci.org SSL cert DCV

README.adoc, plans/evergreen.tf, plans/machine_ci.tf, scripts/terraform
This is basically just copying the great work that @olblak already did for the
cert.ci instance.
=> Add a ci.jenkins.io master VM

plans/dns_jenkinsio.tf, plans/provider.tf, plans/release-core.tf
* Bump azurerm provider to latest stable
* Fix CNAME record
* Add release certificate and gpg key (still in testing)
=> Add release core resources

plans/provider.tf, plans/publick8s.tf
This PR implies to have to delete & create the aks cluster 'publick8s'
=> Enable ASK autoscaling and Windows node

plans/ci.tf
This change re-align with some changes manually applied via portal.azure.com
=> Resize ci.jenkins.io

plans/dns_jenkinsio.tf
=> Don't add jenkins.io to ci.private

plans/dns_jenkinsio.tf
Adding incrementals DNS record for new incrementals publisher application that is being migrated from Azure
=> Add incrementals DNS record

plans/publick8s.tf
tf code didn't match what was there anyway :shipit:
=> Upgrade k8s version

plans/vnets-nsg.tf
Signed-off-by: Olivier Vernin <olivier@vernin.me>
=> Open rsyncd port on k8s cluster

plans/publick8s.tf
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
Related to https://github.com/jenkins-infra/charts/pull/867 (comment https://github.com/jenkins-infra/charts/pull/867#discussion_r579265322)
=> [INFRA-2743] Add a new public IP for the publick8s's new ingress controller

plans/dns_jenkinsio.tf
They emailed me data to get entered into the domain to allow claiming of ownership
=> Add validation TXT entry for libera.chat

CODEOWNERS
Part of https://github.com/jenkins-infra/helpdesk/issues/2829
=> chore: add "terraform" and "kubernetes" teams to CODEOWNERS

rating.jenkins.io.tf
change output to match the yaml for helm
=> fix(rating): reformat secrets output for sops

rating.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/1627
=> fix(rating): Dbconfig infos with correct username

rating.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/1627
=> fix(rating): correct password special characters not fitting php

.terraform.lock.hcl, keycloak.jenkins.io.tf
create a dedicated bdd on the flexible postgresql public instance on azure.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3214
=> feat(keycloak): add a new database

Jenkinsfile_k8s
Reverts jenkins-infra/azure#216 as #214 is ready.
=> Revert "chore: temporary disable the terraform part"

dns.tf, locals.tf, privatek8s.tf, providers.tf, variables.tf, vnets.tf
Note: an updatecli manifest will have to be added to follow [the kubernetes patch versions](https://github.com/jenkins-infra/azure/pull/214/files#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288eR8).
=> feat: add privatek8s cluster

privatek8s.tf, providers.tf, versions.tf
=> feat(privatek8s): add `managed-csi-premium-retain` storage class

privatek8s.tf, providers.tf, vnets.tf
Follow-up of https://github.com/jenkins-infra/helpdesk/issues/2924
=> chore: use new private vnet for `privatek8s` cluster

README.adoc
Ref: https://github.com/jenkins-infra/helpdesk/issues/2924
=> chore: add reference to jenkins-infra/azure-net in the README

privatek8s.tf
=> fix(privatek8s): correct subnet CIDR

privatek8s.tf
ref. https://learn.microsoft.com/en-us/azure/aks/configure-kubenet-dual-stack?tabs=azure-cli%2Ckubectl#limitations
=> fixup: no IPv6 for privatek8s, not yet compatible with Windows nodes

vnets.tf
=> fixup: remove azure-net vnets data

vnets.tf
=> fixup: tmp remove azure-net rg data

vnets.tf
Follow-up of https://github.com/jenkins-infra/azure-net/pull/11
=> chore: restore rg and vnet data from azure-net

archives.tf
> The storage account named archives is already taken.
=> fix(archives): unique storage account name

archives.tf, locals.tf, vnets.tf
can't access containers otherwise
=> fix: restrict access to `archives` storage account

locals.tf, privatek8s.tf, vnets.tf
=> cleanup: remove `temp-privatek8s` remaining references

privatek8s.tf
Avoid terraform changes while remaining correct for the storage account (cf https://github.com/jenkins-infra/azure/pull/264#issuecomment-1401712541)
=> chore: CIDR format for allowed admin IPs

trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3416
=> hotfix(trusted.ci) correct the type of password for the SP

publick8s.tf
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/storage_class#allow_volume_expansion
as per https://github.com/jenkins-infra/helpdesk/issues/3425#issuecomment-1456373704
=> chore(publick8s): ensure that storage class allow volume expansion is explicitly defined

privatek8s.tf
Needed for https://github.com/jenkins-infra/kubernetes-management/pull/3683
=> fix(privatek8s): rename `highmem` node pool to `releasecipool` and increase `linuxpool` max nodes

packer-resources.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3439#issuecomment-1462545769
=> fix(packer): azuread application password object id match the application instead of SP

main.tf, packer-resources.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3439
=> fix(packer) add a role assignement to allow SP to login with a subscription

cert.ci.jenkins.io.tf
As part of https://github.com/jenkins-infra/helpdesk/issues/3395, this PR ensures that the required credentials, allowing the cert.ci.jenkins.io controller, are managed as code.
=> feat(cert.ci.jenkins.io) resources for the controller credential manaing Azure VM agent

privatek8s.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2844
NOTE: that This PR requires the pod templates for jenkins-infra/release
=> feat(privatek8s) update release.ci node pool taints (remove highmem, stick windows pool to release.ci)

infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3421
=> feat(infra.ci): allow to read private vnet

infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3421
correct https://github.com/jenkins-infra/azure/pull/306
=> fix(infra.ci) ensure the custom role assignment for reading networks is created

infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3421
follow up #307
=> fix(infra.ci): ensure the correct contributor rights for resourcegroup

infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3421
=> feat(infra.ci): manage storage account by terraform

locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3471
=> feat(shared image gallery): add an arm64 gallery for ubuntu 20.04

cert.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3470
DO NOT MERGE, need to re-import the storage account before.
`Plan: 0 to add, 1 to change, 0 to destroy.`
=> feat(cert.ci): add storage account to import

locals.tf
as per jenkins-infra/helpdesk#3471
=> feat(shared image gallery): add an arm64 gallery for ubuntu 22.04

locals.tf
=> fix(windows): remove arm galleries as no windows server version available for arm64

trusted.ci.jenkins.io.tf
this set some network rules to allow ssh from admin and deny everything else
=> feat(bounce/trusted): add network rules for bounce

trusted.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/azure/pull/334#discussion_r1179955821 & https://github.com/jenkins-infra/helpdesk/issues/3486#issuecomment-1527088631
=> chore(trusted): add todo comment within code

trusted.ci.jenkins.io.tf
=> feat(trusted): add controller VM with dynamic ip with dynamic DNS record for this private ip

trusted.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/azure/pull/339#discussion_r1184965612 renaming to a more consistent version
=> chore(trusted): rename azurerm_private_dns_zone_virtual_network_link vnet

trusted.ci.jenkins.io.tf
=> feat(trusted): security rules to allow internal SSH connections

trusted.ci.jenkins.io.tf
=> feat(trusted): add cloudinit user-data for vms

trusted.ci.jenkins.io.tf
=> hotfix(trusted.ci.jenkins.io) correct security groups

locals.tf, pgsql.tf, postgres.tf, vnets-nsg.tf, vnets.tf
This PR adds a new postgres server to avoid network overlap issues with the existing "public" one (see https://github.com/jenkins-infra/azure/pull/354#issuecomment-1554549215).
Needs https://github.com/jenkins-infra/azure-net/pull/78
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351
=> feat: add a postgres server

locals.tf
Twin of https://github.com/jenkins-infra/azure-net/pull/81
=> feat(VPN) allow DDU access from secondary workplace

privatek8s.tf
Same as #363 and same "lifecycle" challenges (read the #363 body for details if you want to automate the value for this record)
=> feat(privatek8s) add a DNS record for the private nginx ingress

uplink.jenkins.io.tf
https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1568499546
=> feat: add a managed DB in 'public-db' for uplink.jenkins.io

puppet.jenkins.io.tf
add A and CNAME dns records as code.
=> feat(puppet): add dns record A and cname for puppet.jenkins.io

locals.tf, puppet.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3613
=> fix(puppet) ensure the proper IP is used in NSGs

trusted.ci.jenkins.io.tf
This PR needs the 3 VMs to be either destroyed or tainted before merging
=> cleanup(trusted.ci) change controller hostname for puppet and cleanup code

trusted.ci.jenkins.io.tf
Note that we cannot rename the datadisk (as they already contain data)
=> hotfix(trusted) cleanup VM namings

locals.tf, trusted.ci.jenkins.io.tf
this PR opens the required flows in the NSG
=> hotfix(trusted) allow outbound LDAPs at NSG level

trusted.ci.jenkins.io.tf
This PR makes sure that a new RG and resources are used for the ephemeral agents, in the same region as the trusted controller, with the proper permissions.
=> hotfix(trusted.ci) setup ephemeral agent resources and permissions

trusted.ci.jenkins.io.tf
The NSG was not enabled for the 2 agent subnets. This PR fix this.
- SSH from controller to agent (both permanent and ephemerals) rules are already presents (except name changes)
- Internet access from the agent is allowed
Once merged and deployed:
- The terraform initial apply might fail due to the index of NSG rules: a second apply will fix the issue (as the first one will at least suceeds in deleting the modified rules)
- Validating this PR works as expected once deployed: 
- Reaching the LDAP from the permanent agent should not be possible after deployment (it's possible today:
```bash
curl  ldaps://ldap.jenkins.io
DN:
objectClass: top
objectClass: OpenLDAProotDSE
```
- trusted.ci.jenkins.io can allocate ephemeral …
=> fix(trusted.ci.jenkins.io) apply NSG rules to all subnets of the 'trusted' vnet

ldap.jenkins.io.tf
=> hotfix(ldap): valid Azure resource name

publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3584
=> feat(publick8s): arm64 nodes only available in zone 1

ldap.jenkins.io.tf
Reverts jenkins-infra/azure#396, same error
> shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation
=> Revert "feat(ldap.jenkins.io): add `ldap` File Share to `ldapjenkinsiobackups`"

locals.tf, puppet.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3621, tested manually with success
=> feat(puppet.jenkins.io) allow incoming webhooks gfrom GitHub

locals.tf
=> chore: sort admin IPs and add third IP for lemeurherve

locals.tf
=> Add my current IP address

ci.jenkins.io.tf, custom-roles.tf
Ref. https://github.com/jenkins-infra/azure/pull/413#issuecomment-1604675062
=> hotfix(ci.jenkins.io) fixup of #413

publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3623
imply to add toleration to use this new arm64 node pool as per : https://github.com/jenkins-infra/kubernetes-management/pull/4120
=> feat(publick8s): add a new arm64 pool with taint

ci.jenkins.io.tf
=> fixup(ci.jenkins.io) correct invalid NSG rules

ci.jenkins.io.tf, locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3535
Applied manually
=> hotfix(ci.jenkins.io) persist last settings as code: missing NSGs rules and DNS records

ci.jenkins.io.tf
Applied and tested manually
Fixup of https://github.com/jenkins-infra/azure/pull/424
=> hotfix(ci.jenkins.io) yet another NSG correction

privatek8s.tf
https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1625011472
=> feat(privatek8s) bump Kubernetes from 1.24.9 to 1.25.6

publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3623#issuecomment-1613504371
cleaning old nodepool
=> cleanup(publick8s): remove arm64 old nodepool

updates.jenkins.io.tf
Follow-up of #445 
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1660258021
=> fix(updates.jenkins.io): add `updates-jenkins-io` File Share

ci.jenkins.io.tf, trusted.ci.jenkins.io.tf
This is a preliminary work for https://github.com/jenkins-infra/helpdesk/issues/3688 (to allows cert.ci VM to be reconstructed properly on a gen2 VM).
This PR introduces the use of a terraform module to define a "Jenkins Azure Controller" so our 3 controllers would be easier to manage with the same naming conventions and rules.
A few notes:
- This is a first version of the module with only a small subset of resources (no NSG, no ephemeral agent resources, no Azure AD resources... yet).
- The 'moved' directive have been used to avoid destroying resources in complement with a backward compatibility around naming has been implemented by a renaming of resources for trusted.ci is required
=> feat(ci.jenkins.io, trusted.ci.jenkins.io) use a module for the controller resources

updates.jenkins.io.tf
=> feat(updates.jenkins.io): add `rsyncd.updates` CNAME record in `jenkins.io` DNS zone

cert.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3688
=> feat(cert.ci) use a NAT gateway to ensure scalabale and stable egress system + static outbound IP

custom-roles.tf, vnets.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3690
=> cleanup: removed unused or non-existing resources

trusted.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3624
=> feat(trusted.ci.jenkins.io) ensure that bounce access is passed through private network from VPN

trusted.ci.jenkins.io.tf
https://github.com/jenkins-infra/helpdesk/issues/3624
=> cleanup(trusted.ci.jenkins.io) remove the bounce public IP

updates.jenkins.io.tf
=> chore(updates.jenkins.io): add `digitalocean.updates` CNAME record

publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3719#issuecomment-1727684752
=> feat(publick8s/arm64): increment minimum node for autoscaling to 2

.terraform.lock.hcl, ci.jenkins.io.tf, privatek8s.tf, publick8s.tf, puppet.jenkins.io.tf, trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3753
=> chore: migrate from tfsec to trivy

locals.tf, mysql-public-db.tf, postgres-public-db.tf, vnets.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3602
need https://github.com/jenkins-infra/azure-net/pull/132 from azure-net
=> feat(mysql/flexible): adding a mysql flexible managed instance

updates.jenkins.io.tf
This PR allows to retrieve the URL including the account SAS token needed to interact with the `updates-jenkins-io` file share with `azcopy` (we can't use Azure AD with File Share, nor we want on trusted).
Docs:
- https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json#authorize-azcopy
- https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas
=> feat(updates.jenkins.io): `updates-jenkins-io` Azure File Share SAS

publick8s.tf, updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1803566680
=> feat(publick8s): removing rsyncd as unused

locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1803566680
=> feat(publick8s) upgrade AKS to 1.26.6

publick8s.tf
This PR adds a new node pool in the same compute zone (`3`) as the other node pools used for Intel.
It helps to fix https://github.com/jenkins-infra/kubernetes-management/pull/4698 which shows there is an affinity error between jenkins-weekly's PVC (`useast2-3`) and the current `arm64small2` node pool machines (`useast2-1`) leading to nonscheduled pod.
Note: we kept the same machine sizes as it defaults to 3 machines which is cheaper than 2 "medium sized" machines (medium VM is 2x the time of a small one)
=> feat(publick8s) add a new arm64 node pool in the compute zone 3 

ci.jenkins.io.tf
Fixup of #519 
This PR adds missing permissions allowing the ci.jenkins.io's SP to read the vnet in which it will spawns the agents for the new subscription.
Please note there might be improvement to be done to have this setup in the terraform module for controller in the long term.
Tested and applied locally: i'll self-merge this PR and watch the build on the main branch.
=> fix(ci.jenkins.io) add missing permissions to allow controller reading the agent vnet

contributors.jenkins.io.tf
=> cleanup(contributors.jenkins.io): remove `moved` block

publick8s.tf
first step of [https://github.com/jenkins-infra/helpdesk/issues/3827](https://github.com/jenkins-infra/helpdesk/issues/3827#issuecomment-1840264684)
=> feat(publick8s): add a new systempool with taint

publick8s.tf
correct taint as per https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli#system-and-user-node-pools
follown up #539
=> fixup(publick8s): add the correct taint to the new system pool

publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3827
=> feat(publick8s): remove autoscaling for x86medium nodepool

publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3827#issuecomment-1842725422
=> feat(publick8s): increase node number to 2 for system pool

trusted.ci.jenkins.io.tf
This PR adds the required resources to spawn azure VM agents in the secondary subscription for trusted.ci.jenkins.io.
=> feat(trusted.ci.jenkins.io) add resources to allow spawning azure VM agents in the secondary subscription

cert.ci.jenkins.io.tf
Twin of #548 
This PR adds the required resources to spawn azure VM agents in the secondary subscription for cert.ci.jenkins.io.
=> feat(cert.ci.jenkins.io) add resources to allow spawning azure VM agents in the secondary subscription

infra.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1860472394
Expecting 19 new resources to be created (same as previous PRs for other controllers)
=> feat(infra.ci.jenkins.io) add secondary Azure VM subscription resources

custom-roles.tf, packer-resources.tf
as per https://github.com/jenkins-infra/packer-images/pull/959#issuecomment-1864234391
add role assignment to comply
=> feat(packer): add role assignment for subnet management

infra.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1866680434
This PR adds netowrk security rules to allow packer processes running in the infra.ci *Azure VM* agents to reach packer VMs (in their own subnet) through SSH or WinRM
=> feat(packer) allow SSH and WinRM from infra.ci VM agents to packer VMs

infra.ci.jenkins.io.tf
=> hotfix(infra.ci) missing provider for secondary subscription

updatecli/scripts/date_next_expiry.sh, updatecli/scripts/date_next_startdate.sh, updatecli/scripts/datediff_expiry.sh, updatecli/updatecli.d/contributor.jenkins.io.expiry.yaml, updatecli/updatecli.d/updates.jenkins.io.expiry.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3875#issuecomment-1874329296
=> chore(updatecli): add expiry manifest with date bash scripts

updates.jenkins.io.tf
Fixup of #570 
Related to https://github.com/jenkins-infra/helpdesk/issues/2649 and https://github.com/jenkins-infra/helpdesk/issues/3875
=> hotfix(updates.jenkins.io) SA network restriction must have plain IPs and should not disable public access to apply restriction

updatecli/scripts/date_next_expiry.sh, updatecli/scripts/datediff_expiry.sh
as per https://github.com/jenkins-infra/helpdesk/issues/3875#issuecomment-1874329296
=> chore(updatecli): change date detection for expiry and new certificate lifespan

ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3913
=> feat(ci.jenkins.io): change cname target to new subscription vm

privatek8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3918
for the ARM64 node the price for 1 node all month is around 14$:
﻿﻿![image](https://github.com/jenkins-infra/azure/assets/95630726/dcf8a6fc-7432-4710-b7f8-f6fb24b2864d)
for the intel node the price for 1 node all month is around 33$:
=> feat(privatek8s): minimum count for autoscalling to 1 for spot instances nodes

get.jenkins.io.tf
=> hotfix(get.jenkins.io): set `website` Fiel Share quota to the miminum value 100Gio

jenkins.io.tf
This PR allows the terraform job to interact with the storage account.
Fixup of:
- #623
=> fixup(jenkins.io): add privatek8s subnet in network rules

infra.ci.jenkins.io.tf, plugins.jenkins.io.tf
This PR creates a Premium Storage Account, a File Share and a Service Principal attached to infra.ci.jenkins.io (from where the publication of plugins.jenkins.io is executed)
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1964568638
=> feat(plugins.jenkins.io): new storage

packer-resources.tf
as per calendar event, packer service principle expired
=> fix(packer): bump expiration date for serviceprincipal

locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1991181964
=> bump kubernetes to 1.27.9 for publick8s

plugins.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3999 which fails to deploy with a forbidden error
=> feat(plugin-site) allow infra.ci VM agents to access storage account

privatek8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624
=> feat(privatek8s): add a nodepool dedicated to jenkins controller

privatek8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4046
This PR applies the changes proposed in https://github.com/jenkins-infra/helpdesk/issues/4046#issuecomment-2066810082
=> hotfix(privatek8s) adjust maximum amount if outbound ports

privatek8s.tf
following #672 this PR will confirm that the terraform object have been correctly moved/rename.
will be merge once the move would have been done, and this should show no changes.
=> chore(privatek8s): rename terraform object

trusted.ci.jenkins.io.tf
This PR adds an output with a command to generate a zip containing two env files:
- .env-content for updates-jenkins-io File Share
- .env-redirections for updates-jenkins-io-httpd File Share
This zip file has to be uploaded as zip credentials on trusted.ci.jenkins.io for the update-center2/site/publish.sh script to work.
Ref:
- https://github.com/jenkins-infra/update-center2/pull/777
- https://github.com/jenkins-infra/helpdesk/issues/2649
=> chore(trusted.ci.jenkins.io): ouput to generate a zip of update center env files to access file shares

updatecli/updatecli.d/trusted.ci.sp.endate.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4107
track the expiration date for the controller azure service principal on trusted
=> chore(updatecli): add a manifest to update azure service principal password for the trusted controller

locals.tf, publick8s.tf, weekly.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4044
create a dedicated PVC for weekly.ci that will create a PV and Disk
=> feat(weekly.ci) PVC for weekly.ci.jio

weekly.ci.jenkins.io.tf
following #713 correct wrong azurerm_role_definition id
=> fixup(weekly): use the correct role_definition_resource_id 

updatecli/updatecli.d/trusted.ci.sp.endate.yaml
following #712 more informations
=> chore(updatecli): more information to retrieve credential within terraform

infraci.jenkins.io-kubernetes-sponsored-agents.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3923
and following #715 
this PR create 3 nodes pools:
- application one in arm64
- agents in x86-64
- agents in arm64
=> feat(infra/cluster/sponsored): add node pools

infraci.jenkins.io-kubernetes-sponsored-agents.tf, providers.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3923#issuecomment-2147128098
Plan: 3 to add, 0 to change, 0 to destroy.
add: 
- kubernetes_cluster_role_binding
- kubernetes_secret
- kubernetes_service_account
=> feat(infraci/cluster/sponsored): Add admin service account and token

infraci.jenkins.io-kubernetes-sponsored-agents.tf
as per #715 need to change the os
=> feat(infracijenkinsio-agents-1): change os to azurelinux

ci.jenkins.io-kubernetes-agents.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3954
Twin of https://github.com/jenkins-infra/azure/pull/723, 
this PR fixes the OS to use Azure Linux. It was a mistake I did by forgetting to specify it: as such, the nodes are currently using Ubuntu
=> feat(ci.jenkins.io-kubernetes-agents) change OS of nodes to Azure Linux

privatek8s.tf
following #730 need some formatting
=> chore(privatek8s): terraform fmt

locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2182701643
upgrading the cijio_agents_1 kubernetes cluster and node pools to 1.28.9
=> feat(cijio_agents_1): upgrade to kubernetes 1.28

infra.ci.jenkins.io.tf, trusted.ci.jenkins.io.tf, updatecli/values.yaml
This PR renames existing resources to more descriptive/correct names to avoid mistakes and oversights.
=> chore: rename File Share service principal writers

locals.tf, privatek8s.tf, release.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4044
preparing the migration from premium to standard ZRS
=> feat(releaseci): adding a dedicated disk/pv/pvc for release.ci as standard-zrs

infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4044
preparing the migration from premium to standard ZRS
=> feat(infra.ci): create standard ZRS PV/PVC/DISK for infra.ci

infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4044#issuecomment-2208414161
following #771
=> fix(infraci): correct the resource group for the disk on the main subscription

infra.ci.jenkins.io.tf, ldap.jenkins.io.tf, release.ci.jenkins.io.tf, repo.azure.jenkins.io.tf, weekly.ci.jenkins.io.tf
=> fix: specify PVs and PVCs to use Gi unit to avoid dynamic resizing due to base 1024/1000

updatecli/updatecli.d/fs-sp-writer-end-dates_infra.ci.jenkins.io.tf.tpl, updatecli/updatecli.d/fs-sp-writer-end-dates_trusted.ci.jenkins.io.tf.tpl
=> cleanup(updatecli): remove `shortNextEndDate`

locals.tf, main.tf, providers.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4164#issuecomment-2228458672
This PR cleans up locals which are not used on multiple locations + unused outputs
=> chore: fix Terraform azuread provider errors during terratest execution

test.ci.jenkins.io.tf
Plan: 1 to add, 1 to change, 1 to destroy.
=> chore(test/jay): extending application enddate

ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4204#issuecomment-2281268067
This PR sets up the required Azure Entra permissions and NSG rules to allow ACI agents of ci.jenkins.io to run with a private IP in their dedicated subnet.
=> feat(ci.jenkins.io) support ACI agents with private IP

locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2304516597
=> feat(ci.jio-agents-1) bump AKS to 1.29.7

locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2306465432
=> feat(privatek8s) bump to AKS 1.29.7

locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2306560872
=> feat(publick8s) bump to AKS 1.29.7

publick8s.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4259
Partial revert of https://github.com/jenkins-infra/azure/commit/4058d7f9bf85db67eb9d1d27be0a105c45a75e9b
Needed to avoid our mirrorbits applications to fail restarting on new nodes
=> fix(publick8s) revert back the geopipdata NS and secret to provide storage account credentials for all mirrorbits applications

trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2325103688
This PR adds an Azure private endpoint in agent.trusted.ci network to allow using the `mirrorbits` CLI with the mirrors.updates.jenkins.io service.
Tested  manually with success:
```
$ mirrorbits -h updates.jio-cli.trusted.ci.jenkins.io -a list
Password: ************************************************
Identifier      STATE   SINCE
eastamerica     up      (Tue, 03 Sep 2024 00:05:52 UTC)
westeurope      up      (Mon, 02 Sep 2024 00:20:55 UTC)
```
=> feat(trusted.ci) add a private endpoint to the mirros.updates.jio CLI service

privatek8s.tf, publick8s.tf, updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2352944136
=> feat(updates.jenkins.io) statcially provision PVC for HTTPD

infraci.jenkins.io-kubernetes-sponsored-agents.tf
=> feat(infra.ci/agents/kub) upgrade sku for arm64 nodepool due to errors provisionning

infraci.jenkins.io-kubernetes-sponsored-agents.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4337 following https://github.com/jenkins-infra/azure/pull/857
updates comments and disk available size
=> chore(infra.ci): comments on kubernetes arm64 nodepool

infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/packer-images/pull/1443 from https://github.com/jenkins-infra/helpdesk/issues/4334
we need an azure credential to be able to run az commands in updatecli manifest on packer images.
we scoped this sp to a dedicated empty resource group to avoid a too extensive area of permissions. see https://learn.microsoft.com/en-us/azure/role-based-access-control/scope-overview for reference
=> feat(infra.ci) create a dedicated azure application and sp for updatecli read vm images

trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
Requires https://github.com/jenkins-infra/kubernetes-management/pull/5933
=> feat(trusted.ci) add an Azure Private Endpoint to reach the PLS 'updates-jenkins-io-data'

trusted.ci.jenkins.io.tf
Goal: fixup the main branch build
=> hotfix(trusted.ci.jenkins.io) remove temporarily the Azure PLS

updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
Tested manually with success!
=> feat(updates.jio) add a new NFS storage share and associated publick8s PV/PVC

trusted.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4402
This PR reverts https://github.com/jenkins-infra/azure/commit/e0950bdff5329856a81dd276939e0bc0bf0015c3
It requires https://github.com/jenkins-infra/kubernetes-management/pull/5945 to be merged and deployed
=> feat(trusted.ci.jenkins.io) re enable updates.jio data Private Link

publick8s.tf, updates.jenkins.io.tf
provide a staging storage share to test the cronjob for geoip update without impacting the production storage share (fileshare)
=> feat(publick8s): add a staging fileshare for geoip-data

locals.tf
This PR is applied manually (job disabled)
=> bump AKS from 1.29.7 to 1.29.10

providers.tf
following #905 correct info for mysql access with internal IP
=> chore(providers): correct /etc/hosts line for mysql

updatecli/values.yaml
=> chore(updatecli): correct terraform hcl path

infra.ci.jenkins.io.tf, release.ci.jenkins.io.tf, weekly.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4531
Follow up of #931
=> hotifx(ldap,release.ci,infra.ci,weekly.ci) add write permission to PV disks for respective clusters

ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4315#issuecomment-2656008534
=> feat(ci.jio/migration) migrate cname of ci.jio to aws.ci.jio

locals.tf
see https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663661996
=> feat(cijioagents1) upgrade to kubernetes 1.30.7

locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663185312
=> feat(infracijioagents1): upgrade to kubernetes 1.30

ci.jenkins.io.tf, locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2668175339
=> feat(privatek8s): upgrade to kubernetes 1.30

locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663553626
=> feat(publick8s): upgrade to kubernetes 1.30

ci.jenkins.io-kubernetes-agents.tf, infraci.jenkins.io-kubernetes-sponsored-agents.tf, privatek8s.tf, publick8s.tf
Fixup of #952 
See details in https://github.com/jenkins-infra/azure/pull/952#issuecomment-2701184247
=> hotfix(publick8s,privatek8s,ci.jio-agents-1,infra.ci-agents-1) explicitly define upgrade_override block

vnets.tf
Follow up of https://github.com/jenkins-infra/azure-net/pull/349 to fix the build failing on the principal branch
Ref. https://github.com/jenkins-infra/helpdesk/issues/4313
=> cleanup: remove remnants of ci_jenkins_io vnets

archives.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2757908600
=> feat(archives) add a container storage and allow 'pkg' VM to access the file storage

publick8s.tf, updatecli/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4622
removing the unused volume for staging for cost reduction.
=> feat(publick8s): remove geoip staging volume

ci.jenkins.io-kubernetes-agents.tf
=> fix(ci.jenkins.io-agents-1) switch to x86 nodes to avoid `ZonalAllocationFailed` error

cijenkinsio-agents-1.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4619#issuecomment-2768847941
set the default value as code
=> chore(cijioagents1) set default values for upgrade

cijenkinsio-agents-1.tf, locals.tf, outputs.tf, providers.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619#issuecomment-2773210073
=> feat: add (again) cluster `cijenkinsio-agents-1`

infraci.jenkins.io-kubernetes-sponsored-agents.tf
following #991
we can now use other location for arm64
=> feat(infracijioagents1): change zone for ARM64

infraci.jenkins.io-kubernetes-sponsored-agents.tf
following https://github.com/jenkins-infra/azure/pull/992
=> feat(infracijioagent1): remove arm nodepool from zone 1

locals.tf, providers.tf
Fixup of #986, caught by @smerle33 🥳 ❤️
=> cleanup: remove unused or wrong items accidentally added back when reverting ci.jio

locals.tf, outputs.tf, privatek8s-sponsorship.tf, privatek8s.tf, providers.tf, vnets.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4250
with  https://github.com/jenkins-infra/azure-net/pull/360
create a new privatek8s cluster on the sponsored account
=> feat(privatek8s_sponsorship): add a new cluster privatek8s on the sponsorship account in 1.31.6

ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620
This PR cherry picks the blockers we put in place for https://github.com/jenkins-infra/helpdesk/issues/4575 in the former AWS controller, as we are being abused by these IPs constantly:
```
Error while serving https://assets.ci.jenkins.io/static-files/O_2N5tKxWKfYDoIUxq9va06VjaomytkKWgvKTYZaGGsxNzQ0Mzg4NjY4OTYyOjk6YW5vbnltb3VzOmpvYi9wbHVnaW5zL2pvYi92ZXJhY29kZS1zY2FuLXBsdWdpbi9qb2IvSkVOS0lOUy02ODU0OS9sYXN0U3VjY2Vzc2Z1bEJ1aWxkL2FydGlmYWN0/target/veracode-scan.hpi
java.lang.IllegalStateException: COMMITTED
```
It also cleans up the old SSH rule to aws.ci.jenkins.io (as it has been removed)
=> feat(ci.jenkins.io) block abusive IPs

locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674551720
upgrade the privatek8s cluster to kubernetes 1.31
=> feat(privatek8s): upgrade to kubernetes 1.31

get.jenkins.io.tf, privatek8s-sponsorship.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2797439659
=> feat(privatek8s_sponsorship) add Kubernetes ressources (SA, PVs, PVCs)

locals.tf
see https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674545933
upgrade publick8s to kubernetes 1.31.6
=> feat(publick8s): upgrade to kubernetes 1.31

outputs.tf, privatek8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2839488075
=> cleanup(privatek8s) remove kubernetes only resources to allow deleting provider

privatek8s-sponsorship.tf, publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2839488075
=> cleanup: migrate settings from privatek8s to privatek8s-sponsorship cluster

postgres-public-db.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4667#issuecomment-2894701228
=> feat(postgres-public-db) increase storage to sustain incoming uplinkdb

uplink.jenkins.io.tf
Since we cannot migrate for now: https://github.com/jenkins-infra/helpdesk/issues/4667#issuecomment-2895107678
=> cleanup(uplink) remove the pgsql runtime server

uplink.jenkins.io.tf
Reverts jenkins-infra/azure#1043
Ref. https://github.com/jenkins-infra/helpdesk/issues/4667#issuecomment-2898630045
=> Revert "cleanup(uplink) remove the pgsql runtime server"

uplink.jenkins.io.tf
Reverts jenkins-infra/azure#1044
Not needed by the migration
=> Revert "Revert "cleanup(uplink) remove the pgsql runtime server""

imports.tf, infra.ci.jenkins.io.tf, infraci.jenkins.io-kubernetes-sponsored-agents.tf, vnets.tf
during https://github.com/jenkins-infra/helpdesk/issues/4689
we decided to import the sops vault in terraform to managed it as code.
=> feat(infra.ci.jenkins.io): import sops vault as code

publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4696#issuecomment-2989991496
=> feat(publick8s) enable OIDC to allow using workload identities

reports.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4696
=> feat(reports.jenkins.io) create a new storage account, new RG and also a file share for `builds.reports` with managed identity

reports.jenkins.io.tf
Ref. https://github.com/jenkins-infra/azure/pull/1074/files#r2159366351
(Fixup of #1074)
=> fix(reports.jenkins.io) ensure svc account in `publick8s` uses proper credentials

infraci.jenkins.io-kubernetes-sponsored-agents.tf
Follow up of #1079 to fix tests and cleanup code
Note: will most probably recreate PVC for builds-reports
=> cleanup imports

infra.ci.jenkins.io.tf, infraci.jenkins.io-agents-2.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4696#issuecomment-3007450524
=> fix(infra.ci/infracijenkinsio-agents-2) create federated identity for agents

cert.ci.jenkins.io.tf, outputs.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4693
=> feat(cert.ci) create ressources for azurevm agents in the CDF subscription

infra.ci.jenkins.io.tf, packer-resources.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4701
following: https://github.com/jenkins-infra/azure/pull/1113 and https://github.com/jenkins-infra/azure/pull/1114
fixup the resources groups to cdf
=> fix(packer): correct resource group to cdf subscription

dockerhub-mirror.tf
This PR follows up #1128 which introduced a new keyvault for ACR DockerHub mirror.
Network and RBAC setting shave been reused from infra.ci's keyvault (which fully work in Terraform).
=> fix(dockerhub-mirror) allow managing Key Vault content from infra.ci and from usual admins

outputs.tf
ref. https://github.com/jenkins-infra/helpdesk/issues/4690
=> chore(outputs) add required outputs for the privatek8s (CDF) cluster

infra.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4690
Applied manually (due to infra.ci being down)
=> feat(infra.ci) add a disk,PV,PVC to import data from the data snapshot

release.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4690
=> feat(release.ci) create disk/PV/PVC for migration to CDF subscription

release.ci.jenkins.io.tf
=> chore(release.ci.jenkins.io) remove 'import' directives

get.jenkins.io.tf, outputs.tf, updates.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4767#issuecomment-3180139293
Following up #1158 , now that data has been copied at least once.
=> feat(get.jenkins.io,updates.jenkins.io) create PV/PVCs in the new centralized NFS volume

locals.tf, providers.tf, publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4617#issuecomment-3314747497
=> feat(publick8s) re-create kubernetes resources on new cluster

builds.reports.jenkins.io.tf, contributors.jenkins.io.tf, data-storage-jenkins-io.tf, dockerhub-mirror.tf, docs.jenkins.io.tf, javadoc.jenkins.io.tf, ldap.jenkins.io.tf, plugins.jenkins.io.tf, stats.jenkins.io.tf, www.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4617
=> fix(publick8s) allow new subnets to private resources (storage accounts and ACR)

old_publick8s.tf, publick8s.tf
and set up TTL of all records to 60s while we are there
=> feat(publick8s-endless-ghoul) create custom DNS records for migration

publick8s.tf
Follows https://github.com/jenkins-infra/kubernetes-management/pull/7093
=> feat(publick8s) update DNS record for private-ingress endpoint

publick8s.tf
=> feat(publick8s) move DNS records '*publick8s.jenkins.io' to the new cluster

ldap.jenkins.io.tf, locals.tf, weekly.ci.jenkins.io.tf
=> cleanup(publick8s/ldap/weekly.ci) remove temporary volumes used for migration
