- Jenkinsfile
This will help prevent an error in one Pipeline run from negatively impacting
successive runs for the same pull request.
The downside of this is that resources might be left running in Azure if they
were not capable of being destroyed properly
> Change the tfPrefix for pull requests to ensure that no two are the same

- Makefile
In theory, @olblak believes, this should help us avoid scenarios where the
Azure storage account which Terraform is going to be configured to use does not
properly exist by the time remote state is pushed.
Also extending the wait time to give Azure an extra 30 seconds to register the
remote state storage account
> Avoid parallelism in the bootstrapping for remote state

- Jenkinsfile
I previously forgot that each new pull request is like a whole new Pipeline
whose build numbers start at 1.
> Update the Terraform prefix to include both env.CHANGE_ID and BUILD_ID

- arm_templates/logs.yaml
- plans/logs.tf
- plans/variables.tf
Add azure resources for kubernetes logging workflow.
* Create logs resource group
* Create logs storage account
* Create logs shared disk storage
* Create OMS workspace
More informations can be found within this project
-> [IEP-004](https://github.com/jenkins-infra/iep/pull/5)
We can use this [Project](https://github.com/olblak/k8s) to test this PR.
Keep in mind that we will have to configure secrets properly
N.B.: 
Due to some issues in [fluent-plugin-azurestorage](https://github.com/htgc/fluent-plugin-azurestorage/issues), I choose to use an azure shared disk that I mount at kubernetes level.
We should switch to an azure blob storage if the plugin work as expected.
[This docker image](https://github.com/olblak/fluentd-k8s-azure) implement the logging workflow explain 
[here - …
> Add logs resources provisionning v2.0

- scripts/terraform
The latest 0.9.x doesn't support `terraform remote`
> Pin our terraform container to 0.8.8

- plans/accountapp.tf
Add shared storage 'accountapp'
This shared storage is needed by the accountapp to store election logs.
Linked to following PR:
[Jenkins Infra - #739](https://github.com/jenkins-infra/jenkins-infra/pull/739)
[Accountapp - #104](https://github.com/jenkins-infra/account-app/pull/104)
> Add shared storage 'accountapp' needed to store election logs

- plans/logs.tf
After some triaging by @olblak, it appears that file volumes cannot be mounted
in k8s unless the storage account is in the same region as the k8s cluster.
This commit forces the creation of a new resource, which as @olblak and I
discussed in the ticket, is acceptable in this case since nothing is using this
storage account yet
Fixes INFRA-1186
> Move the logs storage account into the same region as Kubernetes

- plans/pea.tf
Add new ACS cluster.
I explicitly define a resource name different from k8s to avoid confusion and it seems that someone prefer  vegetable over cakes. 
In order to avoid to pay for unused resources, this PR should be merge when we decide to migrate the Kubernetes cluster
> Add a new ACS cluster

- plans/ci.tf
- plans/vnets.tf
This will still need to be somewhat manually bootstrapped with Puppet and then
manually added to trusted.ci
Part of INFRA-1274
> Provision a big trusted-agent in Azure

- plans/ci.tf
- plans/provider.tf
- plans/reports.tf
- plans/vnets.tf
- scripts/terraform
* Remove custom_domain configuration for reports
* Redefine subnet definition for virtual network public_prod
As we can't retrieve a subnet id if declared in a virtual network resource (https://git.io/vNa4F), we split them into separated subnet resources.
And because one of subnet (defined in the virtual network resouce'public_prod') was already referenced from trusted_ci_agent_1, we must follow this order in order to unblock the situation.
1. Create subnet resources
2. Recreate ci_trusted_agent network interface with a reference to the new subnet resource
3. Remove subnet definition from azurerm_virtual_network resource.
Once the state is modified in production, we can redefined the order of resource definition
1. Create virtua_network resource 'public_prod'
2. Create subnet 'data-tier, …
> [Infra-1467] Fix Azure

- plans/remote-state.tf
This is enabled by default for new storage accounts, which led to failures when
running terraform locally.
Splitting separately from my other work.
> Properly enable storage encryption for tfstate

- plans/bean.tf
- plans/ldap.tf
After reevaluation, this storage will only be used to store ldap backups
> [INFRA-1131] Add azure shared storage for ldap

- plans/reports.tf
This doesn't seem to be an issue anymore
> Set custom_domain for reports.jenkins.io only in production

- plans/dns_jenkinsio.tf
The evergreen ssh gateway IP will more than probably change over time, so I suggest to define a dns record for it.
> Add dns: gateway.evergreen

- plans/vnets-nsg.tf
- plans/vnets.tf
This PR introduce various changes on the network groups and security rules:
* Remove deprecrated resource 
> "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.
* Inbound security rule should open destination port instead of source port.
* development environment should block everything coming from the internet excepted port 22 for ssh
* public_dmz need ssh port open from the wild in order to be the ssh entry point for all the machines.
* clean up redundant or useless rules 
* deny-all-internet is redundant with default DenyAllInbound && AllowVNetInBound
* allow-private-ssh is useless with AllowVNetInBound
> Azure network cleanup

- plans/dns_jenkinsio.tf
- plans/machine_vpn.tf
- scripts/init-puppet.sh
This PR describe a vpn machine seated on two subnetworks, one open to  the internet "public_app", and a second closed to the internet.
It also introduce a new dns record "vpn.jenkins.io" in order to reach its public endpoint with a more convenient name.
The purpose of this machine is to deploy an vpn in order to reach hidden service.
This machine is designed to be used with [jenkins-infra/openvpn](https://github.com/jenkins-infra/openvpn) and managed by [jenkins-infra/jenkins-infra](https://github.com/jenkins-infra/jenkins-infra/pull/1204)
> [INFRA-1955] Define an openvpn virtual machine and its dns record

- Jenkinsfile
To prevent multiple infrastructure changes at the same time on the
same environment, this change adds a lock on Jenkins' side.
All builds targeting the same environment/resource type will be applied
in sequential order.
NOTE: This change *requires* Lockable Resources Plugin to be installed.
cc @rtyler @olblak
> Adds a dynamic lock to prevent multiple plans/applies at the same time

- plans/machine_certci.tf
As this ip is in a network that doesn't have port open to the internet, we'll only use it to whitelist connection coming from this machine until prodbean is migrated to a network that doesn't conflict with public prod
> Assign a fixed public ip to cert.ci

- plans/vnets.tf
> NOTE: Subnet <-> Network Security Group associations currently need to be configured on both this resource and using the network_security_group_id field on the azurerm_subnet resource. The next major version of the AzureRM Provider (2.0) will remove the network_security_group_id field from the azurerm_subnet resource such that this resource is used to link resources in future.
[link](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html)
> configure network security group association in two places.

- plans/dns_jenkinsio.tf
I think it safe to switch traffic on azure (once another rsync is done)
> Update ci.jenkins.io endpoint

- plans/publick8s.tf
- plans/vnets.tf
This PR deploys a Kubernetes cluster in a private network in order to deploy services that need to remain private.
We also have to  
* Bump terraform version
* Bump azurerm version
* Update the network security rules to stop deleting/re-creating them during each terraform run 
[This PR implement this design|https://github.com/jenkins-infra/iep/pull/18]
Missing Feature:
[ ] Restrict azure key vault access from private-network
> [INFRA-1657] Deploy a new Kubernetes Cluster

- plans/dns_jenkinsio.tf
private.aks.jenkins.io is the private ingress endpoint only reachable from vpn 
public.aks.jenkins.io is the public ingress endpoint
.jx.release.alpha.jenkins.io endpoints are for experimentation only, related to this [project](https://github.com/olblak/jenkins-release-environment)
> Add new dns record for public aks

- Jenkinsfile
- Makefile
- plans/accountapp.tf
- plans/backups.tf
- plans/bean.tf
- plans/ci.tf
- plans/confluence.tf
- plans/dns_jenkinsci.tf
- plans/dns_jenkinsio.tf
- plans/dockerregistry.tf
- plans/evergreen.tf
- plans/javadoc.tf
- plans/jenkinsio.tf
- plans/ldap.tf
- plans/logs.tf
- plans/machine_certci.tf
- plans/machine_ci.tf
- plans/machine_vpn.tf
- plans/provider.tf
- plans/publick8s.tf
- plans/release-core.tf
- plans/releases-storage.tf
- plans/remote-state.tf
- plans/repo_proxy.tf
- plans/reports.tf
- plans/updates_proxy.tf
- plans/uplink.tf
- plans/variables.tf
- plans/vnets-nsg.tf
- plans/vnets.tf
This PR removed the wildcard DNS record '*.jx.release.alpha.jenkins.io' and replace it with two new records, `[release.repo.jenkins.io](https://release.repo.jenkins.io)` and `[release.ci.jenkins.io](https://release.repo.jenkins.io)`.
Those two records follow the same pattern than the other endpoint like ci.jenkins.io, cert.ci, trusted.ci,...
While initially I wanted to be able to use dynamic dns records for short lived environments, I am now convinced that  for long lived environments, we must use well defined DNS records and the release environment will be a long lived environment. 
Just keep in mind that in the current state, this environment is reachable to everybody who has access to the vpn network and will be move in a more secure place.
PS: Starting from now, this pr also test if …
> Update jenkins release environment dns record

- Makefile
- plans/publick8s.tf
`make prepare` is currently broken because trying to create a storage account that already exist return an error as showned in the following snippet
```
containers.Client#Create: Failure sending request: StatusCode=409 -- Original Error: Error occurred unmarshalling JSON - Error = 'invalid character '<' looking for beginning of value' JSON = '<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.
```
> Allways return true when initiating remote backend

- plans/publick8s.tf
This change is required for windows node 
`Code="AzureCNIOnlyForWindows" Message="Windows agent pools can only be added to AKS clusters using Azure-CNI."`
> Switch publick8s cluster network configuration from kubenetes to azure

- plans/dns_jenkinsio.tf
- plans/provider.tf
- plans/publick8s.tf
I've taken a look at https://github.com/jenkins-infra/azure/pull/121 as discussed here:
https://issues.jenkins-ci.org/browse/INFRA-2357?focusedCommentId=380742&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-380742
The specific error appears to be:
https://github.com/jenkins-infra/azure/pull/121/files#r352280744
But it's probably worth upgrading to the node pool resource 
See the release notes on  why agent_pool_profile is deprecated and  replaced with `azurerm_kubernetes_cluster_node_pool` and  `default_node_pool`
https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v1.37.0
> Upgrade provider, use node pool resource

- Jenkinsfile
Disable terraform apply/destroy from ci.jenkins.io
Tests are systematically not passing because:
* We reach resource limit
* Resource creation timeout
And this leads to a lot of testing resources being provisioned but not cleaned up
> Disable terraform apply from ci.jenkins.io

- plans/remote-state.tf
build is failing due to trying to update a property that can't be updated
[2019-12-11T16:04:30.828Z] * azurerm_storage_account.tfstate_datadog: Error creating Azure Storage Account "infracitfstatedatadog": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="AccountPropertyCannotBeUpdated" Message="The property 'isHnsEnabled' was specified in the input, but it cannot be updated."
> Disable hns

- plans/dns_jenkinsci.tf
- plans/dns_jenkinsio.tf
* Redirect jenkins.io and jenkins-ci.org to publick8s cluster
* Align jenkins.io txt record with manual changes made via portal.azure.com
* Rename release.grafana to grafana.publick8s in order to have one grafana service per cluster
> Update various dns record

- plans/dns_jenkinsio.tf
This pull request is related to different works
* Ldap migration [[INFRA-2364](https://issues.jenkins-ci.org/browse/INFRA-2364)]
* Account app migration [[INFRA-2360](https://issues.jenkins-ci.org/browse/INFRA-2360)]
* Uplink migration [[INFRA-2363](https://issues.jenkins-ci.org/browse/INFRA-2363)]
* Evergreen is deprecated [[INFRA-2362](https://issues.jenkins-ci.org/browse/INFRA-2362)]
* Release.mirrors is currently an experiment with https://github.com/etix/mirrorbits to replace mirrorbrain
! This Pr can only be merge on Monday the 20th of January at 8AM (UTC) as announced [here](http://lists.jenkins-ci.org/pipermail/jenkins-infra/2020-January/001900.html)
> [INFRA-1797] Update various DNS record

- plans/vnets.tf
public_app_tier is less restrictive than public_data_tier and allow ldaps connections.
Currently, I manually modified public_data_tier to allow ldaps connections
> Update publick8s network security group

- plans/dns_jenkinsio.tf
Now that we have a working VPN, it doesn't make sense anymore to allow ssh connection on public IPs
This change create a new dns record to get ci.j.io private IPs
> Add new dns record set to ci.j.io private ip

- plans/dns_jenkinsio.tf
- plans/releases-storage.tf
This pull request defined two DNS records and share storages needed by services running on Kubernetes
* Dns record `get.jenkins.io`  and azure file storage needed for [PR#122](https://github.com/jenkins-infra/charts/pull/122) 
* Dns record `archives.azure.jenkins.io` and azure file storage needed for [PR#130](https://github.com/jenkins-infra/charts/pull/130)
In both cases the data need to be pushed from [here](https://github.com/jenkins-infra/jenkins-infra/blob/8ecc23a590eacddb50e784aeb503f7b9af63d866/dist/profile/files/mirrorbrain/sync.sh#L49)
using **blobxfer**
> Add two share storages: mirrors & archives 

- plans/dns_jenkinsio.tf
Align with manual modification done on portal.azure.com
Second txt record was to validate the azure active directory domain "azure.jenkins.io"
> Add TXT record to validate Fastly certificate

- plans/dns_jenkinsio.tf
As suggested by @timja in https://github.com/jenkinsci/helm-charts/pull/1#discussion_r477222318
this adds a CNAME record which points to helm charts
Part-of: jenkinsci/helm-charts#14
> Add CNAME record charts.jenkins.io

- .gitignore
- .terraform.lock.hcl
- pgsql.tf
- providers.tf
- variables.tf
- versions.tf
- vnets-nsg.tf
- vnets.tf
Part of https://github.com/jenkins-infra/helpdesk/issues/1627 (migrating ratings.jenkins.io from AWS VM to Azure AKS).
This PR adds a postgresql flexible server for the public applications:
- with its own subnet since the azure documentation explains that it must be reserved ("delegated" subnet)
- That subnet should not be reachable from the outside, and would only be allowed incoming connections from AKS subnet.
- Admin and password are generated by terraform (and stored in the encrypted backend state). Please note that the resources of kind `random_password` are considered as sensitive as per [its documentation](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password) and their output hidden from the console log.
- For sizing, we took the default …
> feat(public-pgsql) add a postgresql flexible server instance for the public applications

- pgsql.tf
Ref. https://registry.terraform.io/providers/hashicorp/azurerm/2.99.0/docs/resources/postgresql_flexible_server#zone
> Azure will automatically assign an Availability Zone if one is not specified. If the PostgreSQL Flexible Server fails-over to the Standby Availability Zone, the zone will be updated to reflect the current Primary Availability Zone. You can use [Terraform's ignore_changes functionality](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes) to ignore changes to the zone and high_availability.0.standby_availability_zone fields should you wish for Terraform to not migrate the PostgreSQL Flexible Server back to it's primary Availability Zone after a fail-over.
> fix(public-pgsql) specify explicitly the zone as there are no HA (yet)

- .terraform.lock.hcl
- pgsql.tf
- providers.tf
- vnets.tf
This PR fixes the errors on the principal branches with the following changes:
- Add an explicit dependency to the postgresql server instance that must be created AFTER the DNS private zone link from private network, to avoid egg and chicken problem when running terraform on jenkins agents of the private network
- Fixes the error message `Host not found with X.X.X.X:53` on Jenkins
- Document (as a comment in the provider `postgres`) how to run terraform locally (with a SSH tunnel)
- Fixes the error message `Host not found with X.X.X.X:53` locally
- Correct the DNS<->vnet link from private network: its resource group must be the same as the DNS private zone
- Fix the error message `creating/updating Virtual Network Link "privatevnet-to-publicpgsql" (Private DNS Zone …
> fix(public-pgsql) ensure that network links are created BEFORE dealing with pgsql resources and providers

- .gitignore
- locals.tf
- packer-resources.tf
- vnets.tf
Follow up of https://github.com/jenkins-infra/packer-images/issues/232.
This PR adds tracking, by terraform, of the Azure VM Shared Library images.
- The 3 missing images will be  created once this PR is merged: `staging_ubuntu-20.04`, `staging_windows-2022`, `prod_windows-2022
- All the other shared library had been imported with `terraform import <...> <...>` commands in the production state
- Tags are added to all resource to help us tracking the terraform managed resources
- Please note that some elements are located in US East 2: it's a bit of a mess, because it's the production, and Azure refused to migrate these items to US East. As I did not want to break the production, I've used a local to map the regions per gallery and image: it adds a bit of complexity in the code alas
This …
> Feat: track Azure VM Galleries

- Jenkinsfile_k8s
- We need terraform for updatecli
- Using `latest` for now;: it will always work (and won't be too noisy)
- Long term: we should parse the project to get the latest version. Should be a reusable script from shared tools (so we can do the same trick on all terraform projects)
> hotfix(updatecli) use latest jenkinsciinfra/hashicorp-tools

- README.adoc
- reports.jenkins.io.tf
- updatecli/updatecli.d/terraform-providers.yaml
The service reports.jenkins.io is an Azure Storage Bucket already used by https://github.com/jenkins-infra/infra-reports.
We want to use it for generating more public reports as per https://github.com/jenkins-infra/helpdesk/issues/3087.
This PR adds this bucket and its resource group in the terraform tracking.
> feat(reports.jenkins.io) Track the reports.jenkins.io bucket as per helpdesk 3087

- Jenkinsfile_k8s
Easier for me to work locally without having my cluster erased if/when infra is redeployed (resetting the suspended state of the corresponding job)
> chore: temporary disable the terraform part

- privatek8s.tf
(edit) 💥 this PR destroyes and create a new cluster + IP address (ref. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#os_disk_type => `Changing this forces a new resource to be created`)
As per @lemeurherve diagnostics on the newly created cluster (`privatek8s`), the node pools should use ephemeral system disks as indicated by Azure Best Practises:
This PR sets the system disk type to Ephemeral instead of the default "Managed" as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#os_disk_type.
(edit 2)
Since this PR will re-create the cluster, I've also added another change: we only deploy the node pools to the same zone `3`:
- We do not need "multi-zone" for the private k8s …
> breaking(privatek8s) apply Azure Best Practises on node pools (ephemeral system disks and avoid multi-AZ due to PVs)

- privatek8s.tf
Follow up of https://github.com/jenkins-infra/kubernetes-management/pull/3258 to ensure that the manual operation on `temp-privatek8s` is reported in the automation for the future `privatek8s` cluster.
For the record, command was:
```
az aks nodepool add \
--resource-group prod-jenkins-private-prod \
--cluster-name temp-privatek8s \
--name infracipool \
--priority Spot \
--eviction-policy Delete \
--spot-max-price -1 \
--enable-cluster-autoscaler \
--min-count 0 \
--max-count 20 \
--no-wait \
--node-vm-size Standard_D8s_v3 \
--node-taints jenkins=infra.ci.jenkins.io:NoSchedule
```
> feat(privatek8s) update the `infracipool` configuration (bigger VMs and additional taint)

- privatek8s.tf
- providers.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2844#issuecomment-1326481699.
Removing the kubernetes provider requires to "forget" the storage class with `terraform state rm 'kubernetes_storage_class.managed_csi_premium_retain'` otherwise we have the following error:
```
╷
│ Error: Provider configuration not present
│ 
│ To work with kubernetes_storage_class.managed_csi_premium_retain (orphan) its original provider
│ configuration at provider["registry.terraform.io/hashicorp/kubernetes"].privatek8s is required, but it has
│ been removed. This occurs when a provider configuration is removed while objects created by that provider
│ still exist in the state. Re-add the provider configuration to destroy
│ kubernetes_storage_class.managed_csi_premium_retain (orphan), after which …
```
> cleanup: delete privatek8s cluster.

- archives.tf
- locals.tf
- privatek8s.tf
- providers.tf
- vnets.tf
Now that the new virtual networks and the VPN are ready in https://github.com/jenkins-infra/azure/, I'm adding back the privatek8s cluster, with a restricted access (admins IPS + VPN subnet + current infra.ci.jenkins.io cluster nodes subnet)
See [`5feabaf`](https://github.com/jenkins-infra/azure/pull/248/commits/5feabafe930db99146938bdfe887a7ca266765e1) to review the actual changes.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2844
- https://github.com/jenkins-infra/helpdesk/issues/3257
> feat: add `privatek8s` cluster with restricted access

- privatek8s.tf
🤦 
Fixes this error on https://github.com/jenkins-infra/kubernetes-management/pull/3247 merge build
```
Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"erro
r":{"code":"AuthorizationFailed","message":"The client '1980c7ad-fc64-4e39-a833-1656e5828c47' with object id '1980c7ad-fc64-4e39-a833-1656e5828c47' does not have authorization to perform action 'Microsoft.Ne
twork/virtualNetworks/subnets/read' over scope '/subscriptions/dff2ec18-6a8e-405c-8e45-b7df7465acf0/resourceGroups/private/providers/Microsoft.Network/virtualNetworks/private-vnet/subnets/privatek8s-tier' or
the scope is invalid. If access was recently granted, please refresh your credentials."}}
```
> fix(privatek8s): correct rg and vnet for privatek8s-tier scope

- privatek8s.tf
- vnets.tf
Twin of https://github.com/jenkins-infra/azure-net/pull/27
This PR should NOT change anything: the command
```console
terraform state rm 'azurerm_subnet.privatek8s_tier'
```
was run to avoid managing the network in state anymore.
> Cleanup: migrate privatek8s subnet to jenkins-infra/azure-net

- locals.tf
- privatek8s.tf
This PR ensures that the private-nginx-ingress is allowed to create an internal LB in the private-vnet-data-tier subnet.
Follow up of https://github.com/jenkins-infra/kubernetes-management/pull/3379
Avoid the following error (in the events of the Kubernetes Service of type LoadBalancer for the private-nginx-ingress):
```console
Error syncing load balancer: failed to ensure load balancer: Retriable: false,
RetryAfter: 0s, HTTPStatusCode: 403, RawError:
{"error":{"code":"AuthorizationFailed","message":"The client
'<redacted>' with object id
'<redacted>' does not have authorization to perform
action 'Microsoft.Network/virtualNetworks/subnets/read' over scope
'/subscriptions/<redacted>/resourceGroups/private/providers/Microsoft.Network/virtualNetworks/private-vnet/subnets/private-vnet-data-tie …
```
> fix(privatek8s) allow cluster identity to manage LBs in the data-tier subnet

- privatek8s.tf
This PR fixes the following warning message:
```
Warning: Argument is deprecated
with azurerm_kubernetes_cluster.privatek8s,
on privatek8s.tf line 31, in resource "azurerm_kubernetes_cluster" "privatek8s":
31:   api_server_authorized_ip_ranges = setunion(
32:     values(local.admin_allowed_ips),
33:     data.azurerm_subnet.private_vnet_data_tier.address_prefixes,
34:     # temp-privatek8s nodes subnet
35:     data.azurerm_subnet.default.address_prefixes,
36:     [local.temp_privatek8s_pod_ip]
37:   )
This property has been renamed to `authorized_ip_ranges` within the
`api_server_access_profile` block and will be removed in v4.0 of the provider
```
> fix(privatek8s) correct deprecated 'api_server_access_profile' directive

- publick8s.tf
> fix(publick8s): `kubenet` network plugin, set ephemeral OS disk sizes & address `api_server_authorized_ip_ranges` deprecation notice

- providers.tf
- publick8s.tf
Avoid following error for now:
> Error: Post "[https://publick8s-endless-ghoul-1616a256.hcp.eastus2.azmk8s.io:443/apis/storage.k8s.io/v1/storageclasses](https://publick8s-endless-ghoul-1616a256.hcp.eastus2.azmk8s.io/apis/storage.k8s.io/v1/storageclasses)": dial tcp 20.72.109.139:443: i/o timeout
> 00:10:48.147  │ 
> 00:10:48.147  │   with kubernetes_storage_class.managed_csi_premium_retain_public,
> 00:10:48.147  │   on publick8s.tf line 85, in resource "kubernetes_storage_class" "managed_csi_premium_retain_public":
> 00:10:48.147  │   85: resource "kubernetes_storage_class" "managed_csi_premium_retain_public"
Will restore it after checking this new cluster connectivity.
> chore(publick8s): comment out storage class for now

- privatek8s.tf
Version retrieved with `az aks get-upgrades --resource-group prod-privatek8s --name privatek8s-emerging-ram --output table`
Ref: https://github.com/jenkins-infra/helpdesk/issues/3387
> chore: update `privatek8s` cluster to Kubernetes 1.24

- publick8s.tf
Version retrieved with `az aks get-upgrades --resource-group prod-privatek8s --name privatek8s-emerging-ram --output table`
Ref: https://github.com/jenkins-infra/helpdesk/issues/3387
> chore: update `publick8s` cluster to Kubernetes 1.24

- privatek8s.tf
Fixup of #271 
> Windows agent pool name can not be longer than 6 characters.
> hotfix(`privatek8s`): fix `WindowsAgentPoolNameTooLong` error (#284

- publick8s.tf
- trusted.ci.jenkins.io.tf
- versions.tf
This PR is assorted of the following changes:
- State was cleaned to remove `azuread_application.packer`
- The trusted.ci.jenkins.io SP was re-imported in the state
> fix(trusted.ci) Ensure that "terraform-production" is the explicit owner of the azuread_application

- main.tf
- trusted.ci.jenkins.io.tf
Follow up of #285 and #286  (ref. https://github.com/jenkins-infra/helpdesk/issues/3416#issuecomment-1460801641) .
This PR factorizes the id of the `terraform-production` Service principal to allow reusability
> chore: factorize the terraform-production SP id to allow reusability

- privatek8s.tf
Same mount options as https://github.com/jenkins-infra/helm-charts/blob/a491e7356a304fc2545b175dc90b880a50b727fc/charts/env-jenkins-release/templates/core-packages.yaml#L29-L35, will be used to set storage class in this chart for `release` volumes.
> feat(privatek8s): add `azurefile-csi-premium-retain` storage class

- cert.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3395. 
The cert.ci.jenkins.io controller must be allowed to read the resources in the resoruce group hosting the production packer images.
Former permissions were too extended (scoped to the whole project).
> fix(cert.ci) allow controller to read resources in the production packer resource group

- packer-resources.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3439#issuecomment-1476400705.
This PR adds resource groups for each packer environment and the appropriate permissions for the packer service principals.
The goal is to set the ground for using packer build with the [`build_resource_group_name`](https://developer.hashicorp.com/packer/plugins/builders/azure/arm#build_resource_group_name) attribute to stop creating/deleting resource groups on-the-go and allow scoping permissions only to these resoruce groups (instead of the whole subscription)
> feat(packer) add resource groups for the build resources to scope permissions

- cert.ci.jenkins.io.tf
- main.tf
- packer-resources.tf
- privatek8s.tf
This PR reuses the work by @lemeurherve on the privatek8s resources to ensure that the correct scope syntax is used.
> fix(cert,packer) Fix the role assignement scopes to avoid re-creating on each apply

- privatek8s.tf
Follow-up of https://github.com/jenkins-infra/azure-net/pull/52
Having this dedicated subnet for release.ci.jenkins.io nodes on privatek8s cluster will allow us to finely restrict access to the `prodreleasecore` Azure key vault.
> feat(privatek8s): dedicated subnet for the release.ci node pools

- cert.ci.jenkins.io.tf
- ci.jenkins.io.tf
- custom-roles.tf
- infra.ci.jenkins.io.tf
- providers.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3459
This PR adds the required resources to manage, as code, the credentials and resources required for ci.jenkins.io's agents (VM and ACI).
> feat: track ci.jenkins.io agent resources

- ci.jenkins.io.tf
Fixup of #311 
Related to https://github.com/jenkins-infra/helpdesk/issues/3459#issuecomment-1487228241
> hotfix(ci.jenkins.io) restrict permissions on the public subnet for agents

- packer-resources.tf
see https://github.com/hashicorp/packer-plugin-azure/issues/287#issuecomment-1503705161
https://github.com/jenkins-infra/helpdesk/issues/3471
Terraform plan from https://infra.ci.jenkins.io/job/terraform-jobs/job/azure/job/PR-323/2/artifact/terraform-plan-for-humans.txt :
```terraform
-/+ resource "azurerm_shared_image" "jenkins_agent_images" {
- accelerated_network_support_enabled = false -> null
~ architecture                        = "x64" -> "Arm64" # forces replacement
```
> Set arm64 on image definition

- locals.tf
As part of https://github.com/jenkins-infra/helpdesk/issues/2982, we were able to switch to Ubuntu 22.04.
Let's remove remnants of Ubuntu 20.x manged images: less credits to pay for unused rersources
> cleanup(packer) remove Ubuntu 20.x managed VM images from galleries

- locals.tf
add galleries for amd64 and arm64 for windows also as it's now mandatory to have the architecture within the gallery name for our packer to upload images.
windows ARM64 is not used yet.
> feat(shared images galleries): add amd64 and arm64 galleries

- privatek8s.tf
Following the switch to a percentage based alerting for the available disk size in https://github.com/jenkins-infra/datadog/pull/168, we've noticed the available disk space on linuxpool is below 20% (currently at 16,7%)
This PR is increasing the OS disk size on this node pool.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3497
> fix: increase linuxpool disk size from 30GB to 40GB

- privatek8s.tf
Follow up of https://github.com/jenkins-infra/azure/pull/329: it had a positive impact but we still receive warnings.
>  fix(privatek8s) increase linuxpool disk size from 40GB to 50GB

- trusted.ci.jenkins.io.tf
following https://github.com/jenkins-infra/azure/pull/333 and https://github.com/jenkins-infra/azure/pull/334
adding a controller VM
> feat(trusted): controller VM

- trusted.ci.jenkins.io.tf
and https://github.com/jenkins-infra/azure/pull/338#discussion_r1182794101
we defined a specific internal dns a record for the controller 
to be merge only when main will build
> feat(trusted): add a private dns record for the controller

- privatek8s.tf
Surfaced by https://github.com/jenkins-infra/helpdesk/issues/3539, this PR increases the available disk disk for `linuxpool` (and NOT `systempool`).
Since we pay for 64 Gb, let's use it!
Applied locally, will be merged "as it"
> hotfix(privatek8s) increase linuxpool disk size to 64 Gb

- ci.jenkins.io.tf
- locals.tf
- trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3535, this PR is the first major step to create a new (faster + cheaper) ci.jenkins.io VM managed as code.
Please note the following elements:
- A new resource group is created to avoid messing up with the current one (to avoid any confusion). The goal will be to remove the older resource group once the migration will be complete
- Neither DNS record, subnets or snapshot (of the data disk for migration) are constrained by this
- StandardSSD are used instead of PremiumSSD (V1/V2). The goal is to start with a cheaper storage and see the current IOPS usage (since we [removed the plugin-config-history plugin](https://github.com/jenkins-infra/helpdesk/issues/3528) and [added an S3 artifact caching …
> feat(ci.jenkins.io) define a new VM + datadisk + public IP in a custom resource group

- trusted.ci.jenkins.io.tf
This PR is a fixup of #343 
The Azure portal shows a warning pointing to this setting (`sourcePortRange`), which we missed in the code review.
Outbound port for outgoing SSH connection can be any random port between 1024 to 65000 so we should not block by port.
> fix(trusted.ci.jenkins.io) SSH outbound does not use only 22

- trusted.ci.jenkins.io.tf
This PR is a fixup of #343 .
It allows SSH connections internally (bounce -> controller, controller ->.*-agents) to work as expected by opening the missing outbound connections in the security groups (the inbounds were already specified).
Please note that it also add a 2nd commit which rename the existing inbound rules to make it easier to visually differentiate inbound/outbound rules.
> fix(trusted.ci.jenkins.io) add missing outbound rules to allow SSH internally

- trusted.ci.jenkins.io.tf
Follow up of #350 and #351, fixup of #343
Please note that the ^private DNS record was incorrect and is fixed in this PR.
> fix(trusted.ci.jenkins.io) allow access from bounce to the permanent agent

- locals.tf
- trusted.ci.jenkins.io.tf
This PR fine tune the security groups to:
- Forbid everything by default
- Allow Bounce to reach the controller through HTTPS and TCP Inbound protocol
- Allow VMs to reach Internet through HTTP and HTTPS
- Allow VMs to reach the puppet master though the puppet protocol
> feat(trusted.ci.jenkins.io) Fine tune the security groups to restrict everything except explicit rules

- locals.tf
- pgsql.tf
- postgres.tf
- vnets-nsg.tf
- vnets.tf
Reverts jenkins-infra/azure#359
Fixup of #356 
Needs https://github.com/jenkins-infra/azure-net/pull/79/files
Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1557561704
A few changes since #356:
- Database is now named `public-db` as discussed with @lemeurherve 
- Using a "for_each" struct to define 3 DNS private links for each of the 3 vnets where it is needed
- Grouping Pgsql only resources into the file (except of locals)
> feat: add a new PostgreSQL database (Revert "Revert "feat: add a postgres server"")

- publick8s.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1562482092
This PR adds a DNS record for the private Nginx ingress of the `publick8s` cluster. 
It's required to migrate keycloak (which exposes the `admin.accounts.jenkins.io` ingress through the private-nginx).
Please note the following elements:
- Nit: this PR renames the 2 terraform resources for the existing DNS records of the public loadbalancer, to have homogeneous names
- Will need a subsequent PR to delete the `moved` blocks once applied
- The private IP is written "raw": automation of this could be done through [AKS](https://learn.microsoft.com/en-us/azure/aks/static-ip#apply-a-dns-label-to-the-service) or as seen below, but it's not needed immediatly at all:
- The change of value for this one does not …
> feat(publick8s) add a DNS record for the private nginx ingress

- .terraform.lock.hcl
- publick8s.tf
> chore(publick8s) delete 'moved' blocks after migrating their resources

- plugin-health.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3351
This PR adds a managed DB in the `public-db` Postgres instance for the Plugin Helath Score
> feat(plugin-health.jenkins.io) add a managed DB in 'public-db' instance

- rating.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3351
This PR adds a managed DB in the `public-db` Postgres instance for the Rating service
> feat(rating.jenkins.io) add a managed DB in 'public-db' instance

- uplink.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1568847649
This PR fixes the output for `uplink` and the default pgsql role to ease the migration.
> fix(uplink) correct output for proper connection chain

- trusted.ci.jenkins.io.tf
Part of https://github.com/jenkins-infra/helpdesk/issues/3486#issuecomment-1573305761
Despite the LDAP allowed IP being updated to the apparent outbound public IP ofr the controller.trusted VM, the connection is still not allowed.
As explained in https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/default-outbound-access, using the default outbound IP (that is the case of the controller the agents as they do not have Public IPs) is not sustainable:
- The IP can change at any moment
- Microsoft could provide different outbound path with different apparent IPs (which seems to be our case)
- Scalibility is not there.
This PR adds a NAT gateway solution as it is recommended.
----
Notes:
- Our AKS clutsers are using a Loadbalancer outbound IP, which is their default. Based on …
> feat(trusted.ci) add NAT gateway and DNS record to allow deterministic outbound

- trusted.ci.jenkins.io.tf
There already was a public DNS zone acting as authority for `*.trusted.ci.jenkins.io` so better using it to make the `bounce` IN `A` record to be visible for public DNS clients
> fix(trusted) use existing DNS zone for bounce record

- locals.tf
- trusted.ci.jenkins.io.tf
Fixup of #384 to fix the Update Center build errors `ssh: connect to host updates.jenkins.io port 22: Connection timed out`
> fix(trusted.ci.jenkins.io) allow SSH/Rsync from permanent agent to Update Center VM

- trusted.ci.jenkins.io.tf
Fixup of #384 
`tfsec` seems to ignore the restriction to only 1 host IP so let's ignore the rule :'(
> hotfix(trusted.ci) ignore tfsec rules as it seems broken in this case

- ldap.jenkins.io.tf
This PR creates a new storage account in its own resource group to store LDAP backups (LDIF dumps) instead of the existing `prodldap` one in the `prodldap` resource group, with network access limited to the admin IPs and to the publick8s cluster.
Follow-up of https://github.com/jenkins-infra/azure/pull/385#issuecomment-1577251779
Needs https://github.com/jenkins-infra/azure-net/pull/96
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
> feat: add LDAP resource group and storage account with separated network rules

- ldap.jenkins.io.tf
This PR is to improve quality of life. It avoids the need to manually retrieve this key via Azure Portal or `az-cli`.
Follow-up of #392
> chore(ldap): add storage account primary access key as sensitive output

- ldap.jenkins.io.tf
Reverts jenkins-infra/azure#394
Error encountered:
> Error: checking for existence of existing Storage Share "ldap" (Account "ldapjenkinsiobackups" / Resource Group "ldap"): shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.
> Revert "feat(ldap.jenkins.io): add `ldap` File Share to `ldapjenkinsiobackups`"

- ldap.jenkins.io.tf
This PR adds `ldap` File Share to `ldapjenkinsiobackups` Storage Account.
Needed for https://github.com/jenkins-infra/kubernetes-management/pull/4044
Follow-up of #392 and #394 with privatek8s subnet in storage account network_rules to avoid the following error:
> Error: checking for existence of existing Storage Share "ldap" (Account "ldapjenkinsiobackups" / Resource Group "ldap"): shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
> feat(ldap.jenkins.io): add ldap File Share to ldapjenkinsiobackups

- ldap.jenkins.io.tf
Same as #394 (I'd like to try it first without adding privatek8s subnet to the network rules like in #396), but this time with the `Storage Account Contributor` role added to the Azure terraform agent (commit in the private repo: https://github.com/jenkins-infra/terraform-states/commit/23bfdcee2f166b93d635a80c9c1851bfb6e67d6c) to avoid the following error:
> Error: checking for existence of existing Storage Share "ldap" (Account "ldapjenkinsiobackups" / Resource Group "ldap"): shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.
This PR adds `ldap` File Share to `ldapjenkinsiobackups` Storage Account. …
> feat(ldap.jenkins.io): add `ldap` File Share to `ldapjenkinsiobackups`

- ldap.jenkins.io.tf
This PR adds a public IPv4 dedicated to LDAP which can be used to expose the service from `publick8s`, cf suggestion from @dduportal in https://github.com/jenkins-infra/kubernetes-management/pull/4044#discussion_r1220996916
> feat(ldap): add public IPv4

- locals.tf
- trusted.ci.jenkins.io.tf
As per https://github.com/jenkins-infra/helpdesk/issues/3622, the controller trusted.ci.jenkins.io is having issues.
These issues are caused to connections timing out when trying to reach ldap.jenkins.io in the 636 port:
```
Jun 13 06:52:27 controller docker-jenkins[8264]: Caused: org.springframework.ldap.CommunicationException: ldap.jenkins.io:636; nested exception is javax.naming.CommunicationException: ldap.jenkins.io:636 [Root exception is java.net.SocketTimeoutException: connect timed out]
```
It's because we migrated the LDAP which changed its IP.
Thanks to https://github.com/jenkins-infra/azure/pull/400, the LDAP external IP is now part of the Terraform resources: let's use it to ensure that NSGs of trusted.ci.jenkins.io are always up to date.
> fix(ldap,trusted) use the new public_ip resource for the LDAP connection from trusted.ci

- locals.tf
- trusted.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/azure/pull/406
removing the local as it's used only once.
> chore(puppermaster): remove local for ip as used only once

- locals.tf
- trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3624 (short fix).
It avoids impractical PRs such as #409 and the subsequent Terraform rework that would have make a list concatenation between "admin" and "trusted.ci users" public IPs.
> fix(trusted.ci) lift SSH restrictions and cleanup admin allowed public IPs

- ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3535#issuecomment-1591610874 as we need a resource group  and storage account in the same region as the subnet to use for agents in the public-vnet.
First (required) step is to rename the references to the "old" agent resources for ci.jenkins.io.
The idea is to prefix them using the location (until it's cleaned).
> chore(ci.jenkins.io) rename agent resources to mark their location

- cert.ci.jenkins.io.tf
- ci.jenkins.io.tf
- custom-roles.tf
- infra.ci.jenkins.io.tf
- packer-resources.tf
- privatek8s.tf
- publick8s.tf
- trusted.ci.jenkins.io.tf
As per https://github.com/jenkins-infra/azure/pull/412, the `id` atttributes works as expected for scopes
Thanks @timja !
> chore: simplify role_assignment scopes 

- ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3535#issuecomment-1591610874
Follow-up of https://github.com/jenkins-infra/azure/pull/412
This PR creates the required resources for the ephemeral agents for ci.jenkins.io in US East 2 in the new public-vnet network
> feat(ci.jenkins.io) add required resources for ephemeral Azure VM agents in the new public-vnet

- publick8s.tf
Until ingress works with direct IPv6 (ref. https://github.com/jenkins-infra/helpdesk/issues/3639\#issuecomment-1610982919)
> hotfix(publick8s) remove AAAA (IPv6) DNS record for `get.jenkins.io`

- publick8s.tf
Reverts jenkins-infra/azure#417
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/4116
Ref: https://github.com/jenkins-infra/helpdesk/issues/3639
> Revert "hotfix(publick8s) remove AAAA (IPv6) DNS record for `get.jenkins.io`"

- ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3535
- Adds 2 DNS A records to reach the VM (without changing ci.jenkins.io, yet)
- Rename resources to stick to the "controller" naming like we did with trusted.ci (the proposal to make a module from @timja makes sense for a controller setup as we instantiate it 3 times, so let's get trusted and CI close in order to make the module happen later)
- Set up a first set of NSG rules to controler outbound
> breaking(ci.jenkins.io) bootstrap the new Gen2 VM

- ci.jenkins.io.tf
Since #423 , the (manually created) NSGs allowing inbound SSH from vnet were removed. It is expected but I forgot to add the proper rule to allow access from the VPN.
This PR solves this problem, so we can, again, reach the `private.controller.ci.jenkins.io` domain from the Private VPN.
> fix(ci.jenkins.io) allow inbound SSH from VPN

- privatek8s.tf
Caught by https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1625011472.
The goal is to avoid having to manually upgrade the nodepools in the UI.
> feat(privatek8s) pin nodepool kube versions to automate upgrades

- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1625011472
> fix(publick8s) specify pod subnets explicitly

- ci.jenkins.io.tf
- privatek8s.tf
- publick8s.tf
- puppet.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1629210833
Notes:
- The public IPs on trusted.ci (for the inbound SSH to bounce VM and for the subnet's gateway) are not required to be locked
- Additional locks might be added to the data disks of ci.j or trusted.ci.j for instance, as part of https://github.com/jenkins-infra/helpdesk/issues/3479 if this works as expected
> feat(locks) add locks on all public IPs that should not change

- ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3535#issuecomment-1629312380
This PR removes:
- The storage account `cijenkinsiovmagents` which was used by the Azure VM plugin of the former VM
- The resource group `eastus-cijenkinsio` which was used by the Azure VM and ACI plugins of the former VM
> cleanup(ci.jenkins.io) remove leftovers from the former Gen1 VM

- vnets.tf
Some old (and empty) resources managed manually have been deleted in Azure.
This PR ensures that these resources are not referenced anymore to fix the builds.
> fix: remove deleted and manually managed resources

- ci.jenkins.io.tf
Fixup of #436  which failed with the following error message:
```
│ Error: creating/updating Security Rule (Subscription: "****"
│ Resource Group Name: "public"
│ Network Security Group Name: "public-vnet-ci_jenkins_io_agents"
│ Security Rule Name: "allow-outbound-hkp-udp-from-ci_jenkins_io_ephemeral_agents-subnet-to-internet"): performing CreateOrUpdate: unexpected status 400 with error: SecurityRuleConflict: Security rule allow-outbound-ssh-from-ci_jenkins_io_ephemeral_agents-subnet-to-internet conflicts with rule allow-outbound-hkp-udp-from-ci_jenkins_io_ephemeral_agents-subnet-to-internet. Rules cannot have the same Priority and Direction. To learn more, see aka.ms/nsgrules.
│ 
│   with azurerm_network_security_rule.allow_outbound_hkp_udp_from_ci_jenkins_io_ephemeral_agents_subnet_to_i …
```
> fix(ci.jenkins.io) correct outbound NSG rules order and cleanup

- updates.jenkins.io.tf
> feat: add `updates.jenkins.io` storage account, redis database and CNAME record

- updates.jenkins.io.tf
Fix the following error when trying to deploy https://github.com/jenkins-infra/kubernetes-management/pull/4211:
> UTC Database is down: dial tcp 52.184.161.24:6379: i/o timeout
This is the same settings (allow non SSL) which is currently configured for the mirrorbits database.
Manually tested via Azure Portal, current settings:
Settings with this change:
Connection OK.
> fix(updates.jenkins.io): allow non SSL connections to Redis

- privatek8s.tf
- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3679
Same as https://github.com/jenkins-infra/digitalocean/pull/134 + https://github.com/jenkins-infra/digitalocean/pull/136 but for Azure
Please note that the `privatek8s` SA can be used directly by the pod of jenkins-infra/kubernetes-management by mounting the token in the pod directly.
> refactor(publick8s,privatek8s) define infraciadmin SA with a terraform module

- ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Follow up https://github.com/jenkins-infra/azure/pull/450#discussion_r1296854845
It also fixes the error detected during the apply of #450:
```
Error: creating/updating DNS A Record "controller.trusted.ci" (Zone "trusted.ci.jenkins.io" / Resource Group "trusted"): unexpected status 404 with error: ParentResourceNotFound: Failed to perform 'write' on resource(s) of type 'dnszones/A', because the parent resource '/subscriptions/****/resourceGroups/trusted/providers/Microsoft.Network/dnszones/trusted.ci.jenkins.io' could not be found.
```
> fix(ci.jenkins.io, trusted.ci.jenkins.io) fix controler module initial usage

- ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
> cleanup(ci.j,trusted.ci.j) remove `moved` directives

- ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Follow up of #450 : this PR migrates the "common" controller NSGs into the module.
⚠️ this PR must be applied locally as the NSG deletion/re-creation can be cumbersome.
The expected outcome is a check test with no resources changed (e.G. successfuly apply) and both ci.jenkins.io and trusted.ci.jenkins.io working as expected
> feat(ci.jenkins.io, trusted.ci.jenkins.io) define common NSGs using the controller module

- privatek8s.tf
- publick8s.tf
From https://github.com/jenkins-infra/azure/pull/457#issuecomment-1690063668
> noticed some [automatic scaling] node pools node count changes, will probably add some ignore_changes
> chore: ignore cluster node pools count changes

- publick8s.tf
- updates.jenkins.io.tf
This PR adds a dedicated IP in publick8s nodes resources group for rsyncd (TCP) service and set an A record pointing to it (instead of a CNAME).
Ref: https://github.com/jenkins-infra/helm-charts/issues/625 & https://github.com/jenkins-infra/helpdesk/issues/2649
> feat(updates.jenkins.io): add dedicated IP for rsyncd

- ci.jenkins.io.tf
- locals.tf
- trusted.ci.jenkins.io.tf
Follow up of #456 this PR does 2 things:
- Removal of unused resources (duplicated/commented/etc.)
- Moving the NSG rule allowing SSH from private VPN network to controller and ephemeral agents to the TF module
> cleanup(trusted.ci, ci.jenkins.io) move privatevpn NSGs and remove unused directives

- cert.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3688
A few notes:
- The VM size changed by following the Azure advisory recommandation (except it is a `_v5` instead of `_v4` which is the same as trusted.ci.jenkins.io):
- Data disk set to 128 like trusted.ci.jenkins.io as the current VM does not use a lot of data in the Jenkins home:
```
$ df -h /var/lib/jenkins/
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/jenkins-home  295G   27G  253G  10% /var/lib/jenkins
```
- The new terraform module is used to have the same kind of resources (NSG, VM, etc.) as for ci.jenkins.io and trusted.ci.jenkins.io
> feat(cert.ci.jenkins.io) create a new controller VM and associated resources in the new network

- cert.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3688
This PR is expected to only create a DNS A record for `controller.cert.ci.jenkins.io` in the child DNS zone
> fix(cert.ci.jenkins.io) add a DNS record in the child zone for controller

- cert.ci.jenkins.io.tf
- locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3688, this PR tracks the cert.ci DNS record.
The old record was deleted: it was not managed as code so better to re-create it from scratch.
For history:
> feat(cert.ci) migrate DNS apex to new VM

- publick8s.tf
Reverts jenkins-infra/azure#475
Related to https://github.com/jenkins-infra/helpdesk/issues/3719
Since https://github.com/jenkins-infra/kubernetes-management/pull/4385, we realized that anti affinity is working as expected *if* we configure it properly 😅
This minimum of 2 nodes is not needed anymore then
> Revert "feat(publick8s/arm64): increment minimum node for autoscaling to 2"

- locals.tf
- updates.jenkins.io.tf
This PR allows the creation of NS records for each CloudFlare zone created for updates.jenkins.io so the corresponding subdomains can be delegated to CloudFlare.
Follow-up of https://github.com/jenkins-infra/cloudflare/pull/13
> feat(updates.jenkins.io): NS records for CloudFlare zones

- archives.jenkins.io.tf
- dns.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3760
This PR defines the existing `CNAME` DNS records for `archives.jenkins.io` and `archives.jenkins-ci.org`.
These records have been imported in the terraform state. Merging this PR will apply the following changes (only add tags to the records):
```
Terraform will perform the following actions:
~ resource "azurerm_dns_cname_record" "archives_jenkins_io" {
id                  = "/subscriptions/<redacted>/resourceGroups/proddns_jenkinsci/providers/Microsoft.Network/dnsZones/jenkins-ci.org/CNAME/archives"
name                = "archives"
~ tags                = {
+ "repository" = "jenkins-infra/azure"
+ "scope"      = "terraform-managed"
}
}
~ resource "azurerm_dns_cname_record" "archives_jenkins_io" {
id                  = …
```
> feat(archives.jenkins.io) import existing CNAME records for archives jenkins.io and archives.jenkins-ci.org

- updates.jenkins.io.tf
This PR updates `westeurope.cloudflare.jenkins.io` nameservers which changed after its recreation in CloudFlare.
> chore(updates.jenkins.io): update `westeurope.cloudflare.jenkins.io` nameservers

- archives.tf
- ldap.jenkins.io.tf
- locals.tf
- main.tf
- privatek8s.tf
- publick8s.tf
- puppet.jenkins.io.tf
Twin of of https://github.com/jenkins-infra/digitalocean/pull/165
This PR is a first try at sharing a set common values across our terraform projects.
A new [data-only Terraform module](https://developer.hashicorp.com/terraform/language/modules/develop/composition#data-only-modules) has been added in the jenkins-infra/shared-tools to hold the shared values: https://github.com/jenkins-infra/shared-tools/commit/36589078701232007dbdf8b5034fd93901d072c3.
The following changes are introduced:
- the admin IPs from the shared module are used instead of the locals ones. Ping @smerle33 @lemeurherve can you check the shared module and terraform plan maps to your public IPs (or update them on https://github.com/jenkins-infra/shared-tools/blob/main/terraform/modules/jenkins-infra-shared-data/outputs.t …
> chore: use shared admins from shared-tools module

- updates.jenkins.io.tf
This PR adds `service` as resource type so the account SAS token is accepted for commands like `azcopy list <file-share-url-with-sas-token>`.
It also adds a sensitive output to retrieve the File Share connection string (QoL).
Tested by manually generating tokens from the Azure Portal. (The added `signed_version` comes from these tests)
> fix(updates.jenkins.io): add service as resource type for the SAS token

- updates.jenkins.io.tf
This PR adds an output for the File Share URL, which is needed in combination with the SAS token query string to make requests via `azcopy`.
It also removes the `updates_jenkins_io_storage_account_primary_access_key` output, not needed.
Follow-up of #493 & #494
> chore(updates.jenkins.io): more useful File Share outputs

- updates.jenkins.io.tf
Unfortunately, including an IP restriction on the File Share SAS token results in 403 errors with `azcopy`.
Tested a token without IP restriction, worked as expected.
As the trusted job where I need to use this token is already using other credentials without any IP restriction, and as the workaround isn't trivial (https://github.com/Azure/azure-storage-azcopy/wiki/Troubleshooting---FAQ#workaround-1), this PR removes the IP restriction on this one too.
> chore(updates.jenkins.io): remove IP restriction on File Share SAS token

- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1787324647
This PR allows the trusted.ci agents to reach the `publick8s` cluster API
> feat(publick8s) allow trusted.ci.jenkins.io agents to reach control plane

- publick8s.tf
This PR avoids to update the cluster on each `terraform apply`
> fix(publick8s) ensure trusted authorized IP uses a CIDR notation

- publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1798182954
migrate the ips in another Ressource Group to be able to upgrade kubernetes and avoid locks
> feat(publick8s): migrate public ips to new ressource group prod_public_ips

- cert.ci.jenkins.io.tf
- ci.jenkins.io.tf
- providers.tf
- trusted.ci.jenkins.io.tf
This PR is a (mandatory) preparatory step for https://github.com/jenkins-infra/helpdesk/issues/3818 .
It split the controller/azurevm-agents/aci-agent scopes in 3 terraform modules. The goal is to allow instantiating the (*)agents module for the new sponsorship subscrption without repeating code.
To avoid any breakage on the principal branch (which uses the latest reference of the `main` branch on https://github.com/jenkins-infra/shared-tools/), I've created 3 brand new modules in https://github.com/jenkins-infra/shared-tools/commit/c7ec5b0b350abfb195f191056ad6877073aa1e7c . It should make the PR here autonomous to merge (but the aformentionned commit is also to be reviewed and we can update modules).
💡 A few notes on the introduces changes:
- The ci.jenkins.io's Network Security Group …
> feat(ci.j, trusted.ci and cert.ci) migrate to separated tf modules for agents management in Azure

- ci.jenkins.io.tf
- vnets.tf
This PR adds resources for ci.jenkins.io in the "sponsorship" subscription to allow spinning up azure-vm and aci agents
> feat(ci.jenkins.io) add resources for azure-vm agents in the new sponsorship subscription

- contributors.jenkins.io.tf
This PR adds the File Share that will be used by the nginx-website release on publick8s cluster to serve on contributors.origin.jenkins.io the content generated in https://github.com/jenkins-infra/contributor-spotlight/.
It also rename the storage account resource to be uniform.
Follow-up of #523 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561
> feat(contributors.jenkins.io): add File Share

- contributors.jenkins.io.tf
This PR adds outputs to retrieve fine grained File Share SAS token so we can use azcopy instead of blobxfer and entire Storage Account access key.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561
> chore(contributors.jenkins.io): add SAS token output

- contributors.jenkins.io.tf
- updates.jenkins.io.tf
As these URL aren't sensitive and can already be obtained from public info in this repo, this PR removes the `sensitive` property of the corresponding outputs.
```console
$ terraform output updates_jenkins_io_share_url
"https://updatesjenkinsio.file.core.windows.net/updates-jenkins-io"
$ terraform output contributors_jenkins_io_share_url
"https://contributorsjenkinsio.file.core.windows.net/contributors-jenkins-io"
```
> chore: set File Share URLs as not sensitive

- cert.ci.jenkins.io.tf
- contributors.jenkins.io.tf
- trusted.ci.jenkins.io.tf
- updates.jenkins.io.tf
While working on the Terraform module split in https://github.com/jenkins-infra/helpdesk/issues/3818, it appeared that some unneeded (and unused) resources were creating by the "former module".
The migration to the "3 distinct modules" kept the resources, but this PR removes them as we won't need to use ACI with trusted and cert.
> cleanup: remove unused ACI resources for trusted.ci and cert.ci

- ci.jenkins.io.tf
This PR adds the required resources (AzureAD roles and permissions) in the secondary "sponsored" subscription to allow ci.jenkins.io to use ACI for ephemeral agents.
Note: We are reusing the same resource group as the azure-agents.
> feat(ci.jenkins.io) add ACI agent resources in the secondary (sponsored) subscription

- ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1855950963
Caught while testing the new azure VM agent cloud on trusted.ci: the agent were created but the controller wasn't able to reach them.
Not seen on ci.jenkins.io because agents are using the inbound launcher while trusted.ci uses SSH launcher.
> hotfix(ci.j, trusted.ci.j) ensure controller can reach agent with SSH

- cert.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3818
Twin of #550
> hotfix(cert.ci.jenkins.io) allow controller to reach ephemeral agents in the second subscription with SSH

- infra.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1860472394
Fixup of #554 , this PRs fixes the failing build on the main branch (not caught by `terraform plan` because it is an HTTP/400)
> fix(infra.ci.jenkins.io) fixup of #554 by using correct SP ID and scopes for role assignements

- packer-resources.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3818
this PR moves the packer-builds resources groups to the new subscription.
the goal is too fix build errors on jenkins-infra/packer-images for windows machines (winRM timeout)
> feat(packer): move packer-builds to the new provider azure sponsored

- trusted.ci.jenkins.io.tf
This PR uses https://github.com/jenkins-infra/shared-tools/pull/131 to allow trusted.ci.jenkins.io to manipulate the File Share content of updates.jenkins.io
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1856196680
> feat: allow trusted.ci.jenkins.io to manipulate storage

- locals.tf
- packer-resources.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1864023952
This PR creates the shared gallery in the new subscription:
- 3 resource groups (dev, staging and prod) with one gallery each
- 4 images on each gallery
IMPORTANT: this PR sets the ground to move everything to US East 2 (faster packer builds and we don't use East US since 1.5 years for agents). It cannot do all "eastus" -> "eastus**2**" changes yet though as changing location marks a resource group/gallery to be deleted, while we only want to create new resources (terraform forgets the old resource when only changing provider).
IMPORTANT (2): I've removed the 4 role assignments which are required for the 4 controllers (ci, trusted, cert and infra) to read the shared gallery to spin up agent. The build >= 3 …
> feat(packer) create image galleries in the new subscription

- locals.tf
- packer-resources.tf
Follow up of #560 
Ref. https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1866118776
This PR ensures that all the packer resources defined in the new subscription (and only these) are migrated to US East 2 to solve errors found in https://github.com/jenkins-infra/packer-images/pull/959
Expecting 23 resources to be re-created:
- 4 RGs on the 6 are in us east today
- 4 role assignements (as the 4 RGs changed)
- 3 galleries
- 12 images (4 per gallery
> feat(packer) migrate all resources to `eastus2`

- cert.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
While working on https://github.com/jenkins-infra/helpdesk/issues/3875, the need to manage NAT gateways close to network resources appeared.
This PR removes the definitions of the 2 existing NAT gateway so we can start managing them in jenkins-infra/azure-net.
Note that the associated resources (marked as "to be deleted" in the build 1) will be removed manually from the terraform state (see command in the comment below).
Then a 2nd build will be re-triggered before merging, to ensure no changes will be done by this PR.
> cleanup(cert,trusted) migrate NAT gateway management to azure-net

- locals.tf
- publick8s.tf
- updates.jenkins.io.tf
This PR is related to both https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1874074475 and https://github.com/jenkins-infra/helpdesk/issues/3875
It restricts the Azure SA used for updates.jenkins.io to only a few administrative IPs including trusted.ci's 2 networks.
It also allows trusted.ci new network (sponsored) agents to access publick8s controler (for update center)
> feat(updates.jenkins.io) restrict SA to only a few administrative IPs

- updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1879629619 and https://github.com/jenkins-infra/helpdesk/issues/3875.
This PR uses, for Azure SA restriction, internal network routing as Azure Storage Endpoint is available since https://github.com/jenkins-infra/azure-net/pull/190 (instead of public routing through gateway: hence the removal of outbound IPs).
Tested and applied locally: works as expected!
> hotfix(updates.jenkins.io) restrict Azure SA to only the trusted and infra subnets

- updates.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1884905867
This PR adds the `publick8s_tier` subnet in the list of allowed subnet for the `updates-jenkins-io` storage account.
The goal is to avoid the `mount error(13): Permission denied` error when pods are trying to mount the file storage.
> fix(updates.jenkins.io) allow publick8s cluster to reach the `updates.jenkins.io` storage account

- privatek8s.tf
- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3908
This PR tunes the network outbound method used for both `publick8s` and `privatek8s` (using loadbalancers) with:
- TCP idle timeout decrease from 30 min (default) to 4 min to recycle sockets way more often
- Force static allocation of `3200` (and `1600`)  port on the public outbound IPs as per the Azure Metrics (these values are the upper of each amount of SNAT connection diagrams). 
- Note it disable the dynamic allocation: this should be a problem if we have more than 50 nodes per cluster. Not the case for these 2.
> feat(publick8s,privatek8s) set up outbound LB to support more SNAT connections

- publick8s.tf
Fixup of #579 
The documentation at https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#outboundrules states
> Calculate ports per instance as follows:
> Number of frontend IPs * 64K / Number of backend instances
Today, it means: 64000/22 ( 2 node pools with max 10 nodes and 2 system nodes) ~2909
(edit)
Fixes the following error from the apply of #579 
```text
Kubernetes Cluster Name: "publick8s-endless-ghoul"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidLoadBalancerProfileAllocatedOutboundPorts" Message="Load balancer profile allocated ports 3200 is not in an allowable range given the number of nodes and IPs provisioned. Total node count 25 requires 80000 ports but only …
```
> hotfix(publick8s) correct outbound LB SNAT port

- privatek8s.tf
Fixup of #579 
Twin of #580 
The documentation at https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#outboundrules states
> Calculate ports per instance as follows:
> Number of frontend IPs * 64K / Number of backend instances
Today, it means: 64000/44 = ~1454
(edit)
Fixes the following error from the apply of #579 
```text
Kubernetes Cluster Name: "privatek8s-emerging-ram"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidLoadBalancerProfileAllocatedOutboundPorts" Message="Load balancer profile allocated ports 1600 is not in an allowable range given the number of nodes and IPs provisioned. Total node count 50 requires 80000 ports but only 64000 ports are available given 1 …
```
>  hotfix(privatek8s) correct outbound LB SNAT port

- privatek8s.tf
- publick8s.tf
Fixup of #580 
Correct the error
```
Kubernetes Cluster Name: "publick8s-endless-ghoul"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidLoadBalancerProfileAllocatedOutboundPorts" Message="Load balancer profile allocated ports must be a multiple of 8. Refer to https://aka.ms/aks/slb-ports for more details." Target="networkProfile.loadBalancerProfile.allocatedOutboundPorts"
```
🤦
> hotfix(publick8s,privatek8s) set up LB ports amount to valid values

- cert.ci.jenkins.io.tf
- ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Ref. jenkins-infra/helpdesk#3913
Blocked by https://github.com/jenkins-infra/shared-tools/pull/135
This PR expects module to be updated as it sets up providers for the 3 existing controllers
> chore(ci.jenkins.io, trusted.ci.jenkins.io, cert.ci.jenkins.io) update azure VM controller module to support distinct AzureRM provider for DNS

- publick8s.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3908
This PR increases the amount of public IPs used for outbound connection in `publick8s` as a tentative to increase the SNAT exhaustion threshold.
> fix(publick8s) add more public IPs for outbound connection to avoid SNAT exhaustion

- contributors.jenkins.io.tf
This PR backdates contributors.jenkins.io File Share SAS token to a past date in order to check if it revokes the token.
> test(contributors.jenkins.io): revoke SAS token by backdating its expiry date

- ci.jenkins.io.tf
- publick8s.tf
- vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3913
This PR adds a new ci.jenkins.io controller VM in the new subscription.
Blocked by:
- Subnet to add for the controller in the new subscription: https://github.com/jenkins-infra/azure-net/pull/195 
- Update the terraform module for azure vm controllers to support different AzureRM providers between resources and DNS records (Link to be added)
> feat(ci.jenkins.io) add a secondary (empty) VM to prepare moving controller to secondary sponsored subscription

- cert.ci.jenkins.io.tf
- ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Fixup of #583 
This PR migrates the explicit RG definition for ci.jenkins.io controller in the sponsored subscription into the new module introduced in #583 
It also updates, along the way, references to new (properly named) module output `controller_service_principal_id` instead of `controler_service_principal_id`
> hotfix(ci.jenkins.io) migrate controller RG to the module

- contributors.jenkins.io.tf
- updatecli/updatecli.d/contributor.jenkins.io.expiry.yaml
Cf https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview#best-practices-when-using-sas, This PR defines a stored access policy which allows to easily revoke a SAS token by backdating its expiry date cf https://learn.microsoft.com/en-us/rest/api/storageservices/define-stored-access-policy:
> You can also use a stored access policy to revoke a signature after it has been issued.
We can then pass this stored access policy as argument to create a SAS token with `az`:
```
az storage share generate-sas --name updates-jenkins-io --account-name updatesjenkinsio  --https-only --permissions dlrw --policy-name contributorsjenkinsio-stored-access-policy --expiry 2024-01-24T00:00Z
```
(Haven't tested yet if the `permissions` parameter is needed)
Ref:
- …
> chore(contributors.jenkins.io): add a stored access policy to the storage account

- privatek8s.tf
- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3908
This PR adds the NAT gatewat public IP in the allow list for both `publick8s` and `privatek8s` to ensure all requests originated from inside the clusters (autoscaler, nodes healthchecks, API commands for `kubectl logs/exec`, etc.) are allowed to reach the control plane.
> feat(publick8s, privatek8s) allow NAT gateways to AKS API

- infra.ci.jenkins.io.tf
This PR adds contributors.jenkins.io File Share Service Principal Writer to infra.ci.jenkins.io
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
> chore(infra.ci.jenkins.io): add contributors File Share Service Principal Writer

- ci.jenkins.io.tf
- contributors.jenkins.io.tf
The goal of this PR is to recreate  the new (sponsored) VM and ensure it has a proper DNS (and hostname) so that Puppet can manage it properly.
Related to https://github.com/jenkins-infra/helpdesk/issues/3913
> fix(ci.jenkins.io) re-create the new VM (sponsored) with proper DNS

- infra.ci.jenkins.io.tf
This PR sets the misnamed `file_share_id` (it should be renamed to `scope` in another PR) from contributors.jenkins.io File Share id to its resource group id.
It's used in the fileshare-writer module to define the scope of the role assignment given to the service principal.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
> fix(infra.ci.jenkins.io): correct scope on contributors.jenkins.io resource group

- infra.ci.jenkins.io.tf
This PR set `file_share_id` to contributors.jenkins.io File Share's `resource_manager_id` as it's set for the updates.jenkins.io File Share and trusted.ci.jenkins.io service principal: https://github.com/jenkins-infra/azure/blob/4aea9949038d69bd22bf5618a324ddb541f0b69e/trusted.ci.jenkins.io.tf#L84
Fixup of:
- #602 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
> fix(infra.ci.jenkins.io.tf): use File Share's `resource_manager_id` as scope for contributors.jenkins.io

- get.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3917
> feat(get.jenkins.io/storage): new premium storage class for get.jenkins.io

- get.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3917
Fixup of #598 
This PR correct attributes, mainly `account_kind` which must have the value `FileStorage`
> fix(get.jenkins.io) correct SA parameter to allow creation

- contributors.jenkins.io.tf
This PR adds a lifecycle to contributors.jenkins.io file share to ignore its acl changes, recreated identically every time:
```diff
- acl {
- id = "contributorsjenkinsio-stored-access-policy" -> null
- access_policy {
- expiry      = "2024-04-23T00:00:00.0000000Z" -> null
- permissions = "rwdl" -> null
- start       = "2024-01-23T00:00:00.0000000Z" -> null
}
}
+ acl {
+ id = "contributorsjenkinsio-stored-access-policy"
+ access_policy {
+ expiry      = "2024-04-23T00:00:0000000Z"
+ permissions = "rwdl"
+ start       = "2024-01-23T00:00:0000000Z"
}
}
```
Follow-up of:
- #595
> chore(contributors.jenkins.io): use ISO8601 datetime for SA ACL

- get.jenkins.io.tf
This PR recreates the file share deleted in https://github.com/jenkins-infra/helpdesk/issues/3917#issuecomment-1912026208, needed for the Core release process.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3927
> fix: add website file share to getjenkinsio storage account

- get.jenkins.io.tf
- privatek8s.tf
This PR adds release.ci.jenkins.io subnet to `getjenkinsio` storage account's allowed virtual nets, and adds `Storage Account Contributor` role assignment to privatek8s's service principal.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3927
> fix(get-jenkins-io): allow release.ci.jenkins.io to interact with its storage account

- infra.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
This PR sets the new fileshare writer module input variable `storage_account_id`, and rename `file_share_id` to `file_share_resource_manager_id`.
Review without whitespaces changes: https://github.com/jenkins-infra/azure/pull/618/files?diff=unified&w=1
Follow-up of:
- https://github.com/jenkins-infra/shared-tools/pull/143
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1942141701
> fix(contributor/updates): set Storage Account Contributor role for fileshare-writer service principals

- main.tf
- updates.jenkins.io.tf
This PR removes the SAS token as we'll use a service principal to generate a short lived SAS token instead, already added in https://github.com/jenkins-infra/azure/pull/618
This PR also adds the `jenkins` subscription_id and tenant_id so we can retrieve them to create the service principal credentials.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1952035761
> chore(trusted.ci): remove SAS token

- jenkins.io.tf
This PR sets the correct storage account for `jenkins-io` file share.
Fixup of:
- #623
> fixup(jenkins.io): correct storage account for `jenkins-io` file share

- jenkins.io.tf
This PR sets `jenkins-io` file share size to 100Gio, the minimum size when using a Premium storage account.
According to https://azure.microsoft.com/en-us/pricing/details/storage/files/#pricing, this means a cost of $20/month ($0.20 * 100Gio)
Fixup of:
- #623 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
> fixup(jenkins.io): set File Share size to 100Gio (minimum when using Premium)

- javadoc.jenkins.io.tf
- trusted.ci.jenkins.io.tf
This PR creates a Premium Storage Account, a File Share and a Service Principal attached to trusted.ci.jenkins.io (from where the publication of javadoc.jenkins.io is executed)
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1966067802
> feat(javadoc.jenkins.io): new storage

- privatek8s.tf
as per https://github.com/jenkins-infra/jenkins.io/pull/7027/files#r1511135932
and https://github.com/jenkins-infra/kubernetes-management/pull/5035/files
need a bigger node for ARM64 for large pods
(we may need to add a taint and toleration to reserve those nodes for only large pods)
Prices for those large nodes are exactly double of the small ones (264,26$/month)
> feat(privatek8s): adding a large arm64 nodepool

- privatek8s.tf
Reverts jenkins-infra/azure#633
as we have an error : 
```
Plan: 1 to add, 0 to change, 0 to destroy.
azurerm_kubernetes_cluster_node_pool.infracilargearm64: Creating...
Error: 
The Kubernetes/Orchestrator Version "1.26.6" is not available for Node Pool "arm64large".
Please confirm that this version is supported by the Kubernetes Cluster "privatek8s-emerging-ram"
(Resource Group "prod-privatek8s") - which may need to be upgraded first.
The Kubernetes Cluster is running version "1.26.6".
The supported Orchestrator Versions for this Node Pool/supported by this Kubernetes Cluster are:
Node Pools cannot use a version of Kubernetes that is not supported on the Control Plane. More
details can be found at https://aka.ms/version-skew-policy.
with …
```
> Revert "feat(privatek8s): adding a large arm64 nodepool"

- locals.tf
as per https://github.com/jenkins-infra/azure/pull/634 and https://github.com/jenkins-infra/azure/pull/635
need to upgrade to the latest patch version
> bump (privatek8s): patch kubernetes to 1.26.12

- trusted.ci.jenkins.io.tf
This PR renews trusted.ci.jenkins.io controller service principal so it can spawn azure VM agents again.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3982
> hotfix(trusted.ci.jenkins.io): renew controller service principal

- locals.tf
- main.tf
- providers.tf
(edited) This PR ensures that terraform ignores any local `az` CLI subscription custom setup and uses raw values instead
> chore(azurerm providers): specify subscriptions ID as `locals` and update shared tools

- locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1991178802
bump kubernetes to 1.27
> feat(privatek8s): bump kubernetes to 1.27.9 for privatek8s

- infra.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4000
This PR changes the end date of this service principal used by infra.ci.jenkins.io to spin up Azure VM agents to rotate it (regular routine)
> feat(infra.ci.jenkins.io) rotate Jenkins Azure VM Service Principal

- contributors.jenkins.io.tf
- plugins.jenkins.io.tf
Since https://github.com/jenkins-infra/contributor-spotlight/pull/108, the deployment of contributors.jenkins.io fails with an `AuthorizationFailure` (HTTP/403) error from `azcopy`.
This PR applies the same fix as #647 but for contributors.jenkins.io by allowing the infra.ci VM agents to reach the storage account.
Related to the following IM request: https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$7fA7k79pIcRfhFIJOLTS88apzvjt-IYlsBmyBN_43ac?via=g4v.dev&via=gitter.im&via=matrix.org (incoming helpdesk issue to track)
> feat(contributors) allow infra.ci VM agents to access storage account 

- contributors.jenkins.io.tf
This PR removes this output, superseded by the use of https://github.com/jenkins-infra/pipeline-library/blob/master/resources/get-fileshare-signed-url.sh to get the file share URL including a SAS token.
Verification procedure after merging this PR: ensure https://infra.ci.jenkins.io/job/website-jobs/job/contributor-spotlight/ job passes.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-2034806598
> cleanup(contributors.jenkins.io): remove `azurerm_storage_share.contributors_jenkins_io` output

- privatek8s.tf
as per https://learn.microsoft.com/en-us/azure/azure-linux/intro-azure-linux#azure-linux-container-host-key-benefits
AzureLinux OS is lighter and more prone to fast security update.
Lets take advantage to those 2 not yet used nodepool to switch from ubuntu to azurelinux
> chore(privatek8s): change from ubuntu to azure linux the os for the nodes

- infra.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3823
This PR follows up https://github.com/jenkins-infra/kubernetes-management/pull/5126
It fixes the failure to spin up VM agents since the `arm64` migration: as the infra.ci.jenkins.io controller was moved to a new subnet in https://github.com/jenkins-infra/azure/pull/658
> fix(infra.ci.jenkins.io) update NSG to allow arm64 controller to reach agents (new subnet)

- main.tf
As per https://github.com/jenkins-infra/helpdesk/issues/4045#issuecomment-2059732162, the [name of the Azure SP used by Terraform in production for the `azure`project changed](https://github.com/jenkins-infra/terraform-states/commit/bbab9fe5e97ce12d1bdcc9be5581941515e7dbe1)  
This PR updates the code to maps this change
> hotfix: use the new SP name

- updates.jenkins.io.tf
This PR adds a dedicated File Share for httpd.
This will allow us to mount the .htaccess file generated by https://github.com/jenkins-infra/update-center2/blob/master/site/generate-htaccess.sh and completed with https://github.com/jenkins-infra/update-center2/pull/776 only as volume for the `httpd` updates.jenkins.io service, and every other files except .htaccess as volume for the `mirrorbits` updates.jenkins.io service.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2075477428
> chore(updates.jenkins.io): add a dedicated File Share for httpd service

- trusted.ci.jenkins.io.tf
This PR allows trusted.ci.jenkins.io to interract with updates-jenkins-io-httpd File Share.
Follow-up of:
- #676
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2075477428
> chore(updates.jenkins.io): allow trusted.ci.jenkins.io to interract with updates-jenkins-io-httpd File Share

- docs.jenkins.io.tf
This PR adds the storage account and file share that will be used by the nginx-website release on publick8s cluster to serve on docs.origin.jenkins.io the content generated from https://github.com/jenkins-infra/docs.jenkins.io/.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3885#issuecomment-2090052823
> feat: add `docs.jenkins.io` storage account and file share

- updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2090967319
This PR switches to a `Premium` storage account kind for updates.jenkins.io to remove costs related to file storage transactions. The storage costs will increase from $0.09 to $0.50 which is ... affordable... to say the least (compared to the expected decrease of ~$320 transaction cost).
Note:
- The update center job is not trying to update storage
- Services azure.updates.jenkins.io and mirrors.updates.jenkins.io have been uninstalled
> feat!(publick8s/updates.jenkins.io) switch Storage Account to Premium to decrease costs (BREAKING)

- updates.jenkins.io.tf
Fixup of #682 which failed to deploy (HTTP/400 error) when creating the file shares.
As per https://learn.microsoft.com/en-us/azure/storage/files/understanding-billing#provisioning-method, the minimum size for a file share is 100 Gb.
The cost evaluation in https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2090967319 need to be re-evaluated:
- Transactions cost from ~$380 to $0 monthly
- Storage cost from $0.09 monthly to $32 (2 x 100 x 0,16).
> fix(updates.jenkins.io) set FS to minimum size for each

- infra.ci.jenkins.io.tf
This PR creates a service principal to interact with `docs-jenkins-io` File Share expiring in 3 months.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3885#issuecomment-2090052823
> feat: create a service principal to interact with `docs-jenkins-io` File Share

- trusted.ci.jenkins.io.tf
This PR sets a unique name for the service principal application dedicated to the httpd file share with trusted.ci.jenkins.io and output the application id instead of the service principal id.
Fixup of:
- #677
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649
> fix(trusted.ci.jenkins.io): correct name and output for the httpd file share service principal writer

- ci.jenkins.io-kubernetes-agents.tf
- ci.jenkins.io.tf
- locals.tf
- privatek8s.tf
- providers.tf
- publick8s.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3954
Blocked by https://github.com/jenkins-infra/shared-tools/pull/146
This PR introduces a new AKS cluster to host ci.jenkins.io container agents workload with the [specified](https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2095952884) attributes:
- [Private cluster](https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2096296286) (e.g. API not exposed except internally) which means we need cluster to reach it => it might need subsequent PRs to fine-tune the infra.ci.jenkins.io agent network accesses.
- Outbound with NAT gateway and no ingress (as per https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2096296286)
- Initial set of node pools with the [proposed …
> feat: add a new AKS cluster for ci.jenkins.io agents

- ci.jenkins.io-kubernetes-agents.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2107226189
This PR adds managed resources to create a kubernetes cluster-admin account to be used by infra.ci.jenkins.io to run the jenkins-infra/kubernetes-management jobs on the new ci.jio agent 1 cluster.
> feat(ci.jenkins.io - aks-agents-1) create an admin SVCaccount to manage kubernetes resources

- ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3954
After a pairing session with @smerle33 where we discovered that the applications running in the AKS cluster's `kube-system` namespace where failing due to timeouts, we realized that the NSG in charge fo setting up rules for inbound agents is not shaped to handle an AKS cluster as it blocks technical requests within the cluster:
- Pods (`10.100.0.0/14`) to internal DNS (`10.0.0.0`) server
- Kubelet (unknown CIDR) to pods (`10.100.0.0/14`)
- Pods (`10.100.0.0/14`) to Kubernetes services
- Etc.
This PR removes the NSG (for now) until we have deployed the cluster
> fix(ci.jenkins.io-agents-1) remove AKS subnet NSG to avoid kubelet and pod issues

- ci.jenkins.io-kubernetes-agents.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2114950444
This PR fixes the label `role` used by the BOM node pool on the `ci.jenkins.io-kubernetes-agents-1` cluster to ensure we can use a specific `nodeSelector` for the BOM container agents
> fix(ci.jenkins.io-kubernetes-agents) use correct labels for the BOM node pool

- updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3954
This PR removes the `digitalocean.updates.jenkins.io` CNAME DNS record which has been used for [prototyping the new update center](https://github.com/jenkins-infra/helpdesk/issues/2649). As the Digital Ocean clusters have been removed and as we don't need this record, this PR deletes it
> cleanup(updates.jenkins.io) removes the (unused) `digitalocean.updates.jenkins.io` CNAME record

- updates.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2134643950
adding a cname `eastamerica.cloudflare.jenkins.io` to be used within mirrorbits for updatecenter (updates-jenkins-io-mirrorbits)
> feat(cloudflare): add cname for the eastamerica bucket

- weekly.ci.jenkins.io.tf
following #700 and as per https://github.com/jenkins-infra/helpdesk/issues/4044
this PR will allow a pod to access the new PV/PVC/DISK and handle the data migration.
this PR was tested locally, it failed when using both ID and name for the role assignment/role definition, it failed with only the id with `Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRoleDefinitionId" Message="The role definition ID '5a60a9a4-88e7-d46c-6311-6aa2bba1581c|' is not valid."`
but succeeded with only the `role_definition_name` ...
> feat(weekly.ci) add role definition and assignment for new disk access

- ci.jenkins.io-kubernetes-agents.tf
When a cluster has 10+ nodes, the following recommendation pops in Azure portal:
This PR changes the SKU on this cluster to ensure better scheduling performances when BOM builds are running.
The cost can be ignored: it is in the subscription paid by sponsored credits
> feat(ci.jenkins.io-agents1) set AKS SKU to `Standard` instead of `Free`

- infraci.jenkins.io-kubernetes-sponsored-agents.tf
This PR aims to fix the error mentioned in https://github.com/jenkins-infra/azure/pull/715#issuecomment-2158850175
It updates the subnet name used for this cluster as a follow up of https://github.com/jenkins-infra/azure-net/pull/252
> hotfix(infraci.jenkins.io-kubernetes-sponsored-agents) use new subnet (shorter) name

- ci.jenkins.io-kubernetes-agents.tf
- infraci.jenkins.io-kubernetes-sponsored-agents.tf
- privatek8s.tf
- publick8s.tf
as per 
- https://github.com/hashicorp/terraform-provider-azurerm/issues/24020
we are having the same repetitive update on azure, so setting the default should avoir permanent update override
> chore(AKS clusters) explicit upgrade_settings.max_surge to default Azure value for all nodepools to avoid permanent update

- privatek8s.tf
Follow up of #727 , #730 and #731
This fixes the never-ending changed attribute `upgrade_settings {}` for the 2 Spot node pools on `privatek8s`.
It follows the tip found in https://github.com/hashicorp/terraform-provider-azurerm/issues/24020#issuecomment-2158404079 to avoid having all of our plans trying to change the 2 node pools.
> chore(privatek8s) ignore changes for `upgrade_settings` to avoid never-ending updated attribute

- stats.jenkins.io.tf
This PR adds the storage account and file share that will be used by the nginx-website release on publick8s cluster to serve on new.stats.jenkins.io the content generated from https://github.com/jenkins-infra/stats.jenkins.io/.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2167717401
> feat: add `stats.jenkins.io` storage account and file share

- infra.ci.jenkins.io.tf
This PR creates a service principal to interact with `stats-jenkins-io` File Share expiring in 3 months.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2167717401
> feat: create a service principal to interact with `stats-jenkins-io` File Share

- privatek8s.tf
- publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3923
we need to allow new agents from the cluster `infracijenkinsioagents1` to access aks api for privatek8s and publick8s.
> feat(privatek8s/publick8s): allow infracijenkinsioagents1 subnet to reach aks api

- infra.ci.jenkins.io.tf
- locals.tf
- locals.yaml
This PR moves `infra.ci.jenkins.io.tf` service principal end dates to `local.tf` so they can more easily be tracked by updatecli.
In existing manifests tracking end dates, these dates aren't an issue as their name is unique in their file, ex:
https://github.com/jenkins-infra/azure/blob/23b9374f2346839182e8aac1f9628ab758664ceb/ci.jenkins.io.tf#L34C3-L34C40
Retrieved by
https://github.com/jenkins-infra/azure/blob/23b9374f2346839182e8aac1f9628ab758664ceb/updatecli/updatecli.d/ci.sp.endate.yaml#L16-L21
Unfortunately, adding a manifest to take care of https://github.com/jenkins-infra/azure/pull/733#discussion_r1646375931 isn't as easy as there are multiple `service_principal_end_date` in the infra.ci.jenkins.io.tf file.
Hence this PR to regroup them into a map in local.tf so they can be …
> chore: move `infra.ci.jenkins.io.tf` service principal end dates to `local.tf`

- locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2178169723
upgrading the infracijenkinsio_agents_1 kubernetes cluster and node pools to 1.28.9
Plan: 0 to add, 3 to change, 0 to destroy.
> feat(infracijenkinsio_agents_1): upgrade to kubernetes 1.28

- updatecli/updatecli.d/stats.jenkins.io.sp.endate.yaml
This PR adds an updatecli manifest to track `infraci_stats_jenkins_io_fileshare_serviceprincipal_writer` end date.
Proposed PR body:
> ![image](https://github.com/jenkins-infra/azure/assets/91831478/ad015472-2440-466d-b565-0a5c57950010)
Test:
<details><summary>updatecli diff --values updatecli/values.yaml --config updatecli/updatecli.d/stats.jenkins.io.sp.endate.yaml</summary>
```console
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "updatecli/updatecli.d/stats.jenkins.io.sp.endate.yaml"
SCM repository retrieved: 1
++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++
++++++++++++
+ PIPELINE +
++++++++++++
##################################################################################
##################################################################################
SOURCES …
```
> chore(updatecli): track `infraci_stats_jenkins_io_fileshare_serviceprincipal_writer` end date

- updatecli/updatecli.d/fs-sp-writer-end-dates.yaml
This PR adds a generic File Share service principal writer end dates manifest.
PR body with stats.jenkins.io as example:
> ![image](https://github.com/jenkins-infra/azure/assets/91831478/31935fd7-13c2-4675-8813-d9b3c8682b54)
Follow-up of:
- #741
- #737
> chore(updatecli): track all File Share service principal writer `end_date`s

- infraci.jenkins.io-kubernetes-sponsored-agents.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3923
> hotfix(infraci.jenkins.io-kubernetes-sponsored-agents) set min size to 1 for ARM64 node pool to avoid slow auto-scaling

- infra.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
- updatecli/values.yaml
This PR moves `trusted.ci.jenkins.io.tf` service principal writer end dates to `updatecli/values.yaml`.
A dedicated updatecli manifest will be added in a follow-up pull request so it can be properly validated. (Will adapt the existing manifest at the same time)
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4148#issuecomment-2185911564
> chore: move `trusted.ci.jenkins.io.tf` service principal writer end dates to `updatecli/values.yaml`

- updatecli/updatecli.d/fs-sp-writer-end-dates_infra.ci.jenkins.io.tf.yaml
- updatecli/updatecli.d/fs-sp-writer-end-dates_trusted.ci.jenkins.io.tf.yaml
This PR adds a manifest to track the File Share service principal writer end dates defined in trusted.ci.jenkins.io.tf file.
Follow-up of:
- #748
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4148#issuecomment-2185911564
> chore(updatecli): track trusted.ci.jenkins.io.tf File Share service principal writer end-dates

- infra.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
This PR removes service principal id and password outputs and rename application ones to be more descriptive about the fact they concern the application client id and the application client password, not the service principal.
It also removes the `moved` blocks introduced in #754 as these renaming are now in terraform state.
Follow-up of:
- https://github.com/jenkins-infra/shared-tools/pull/150
- #754
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4149
> chore: remove service principal id and password outputs and rename application ones

- publick8s.tf
as we are planning to upgrade to kubernetes 1.28 https://github.com/jenkins-infra/helpdesk/issues/4144, adding the autoscaling may speed up the upgrade, cijioagent1 wasn't with autoscale on the system pool and took 32mn to upgrade (most of it for the 3 nodes system pool).
> chore(publick8s): enable autoscaling for the system pool

- updatecli/updatecli.d/fs-sp-writer-end-dates_infra.ci.jenkins.io.tf.yaml
- updatecli/updatecli.d/fs-sp-writer-end-dates_trusted.ci.jenkins.io.tf.yaml
- updatecli/values.yaml
> chore(updatecli): improve end-dates manifest titles

- ci.jenkins.io-kubernetes-agents.tf
- infraci.jenkins.io-kubernetes-sponsored-agents.tf
during the upgrade to kubernetes 1.28 https://github.com/jenkins-infra/helpdesk/issues/4144, we saw a long time to upgrade system pool and this may be due to the fact that the system pools of those 2 clusters: `cijioagents1` and `infracijioagent1` are not on autoscale.
This may improve next upgrade.
> chore(infracijioagent1/cijioagent1): enable autoscaling for the system pool

- locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2190936375
upgrading the privatek8s kubernetes cluster and node pools to 1.28.9
> feat(privatek8s): upgrade to kubernetes 1.28

- updatecli/updatecli.d/infra.ci.sp.endate.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4154
This PR tracks the end date of the infra.ci.jenkins.io Azure Client Password used to spawn Azure VM agents.
> chore(updatecli) track end date for the Azure client password used by Azure VM agents plugin in infra.ci.jenkins.io

- locals.tf
- weekly.ci.jenkins.io.tf
We have the following rule of thumb in the Jenkins Infra terraform projects: "If a value is duplicated then factorize it as a local". It's a rule of thumb which has been carefully followed which is good 👍 
However in this particular case (weekly.ci persistent resources), the values duplication factorized into a local has an unexpected side-effect: it hides a dependency chain between resources.
This PR fixes it by making the dependency between resources (PVC -> PV -> disk) explicit.
Positive side-effect: it removes the local so the specific values sides within the scope of the weekly.ci.jenkins.io TF file.
We expect no changes in this PR (for the Terraform plan).
> chore(weekly.ci) make resource dependencies explicit by avoiding locals

- updatecli/updatecli.d/fs-sp-writer-end-dates_infra.ci.jenkins.io.tf.yaml
- updatecli/updatecli.d/fs-sp-writer-end-dates_trusted.ci.jenkins.io.tf.yaml
This PR simplifies the Go template used in `updatecli` manifests to have less code, which follows the usual Go conventiojns to ensure any contributor with go background will be at ease. It also prevent potential bugs around variables scope re-entrance in `updatecli` and human mistake (overriding accidentally the `github` values).
Go template system (see https://pkg.go.dev/text/template#hdr-Variables) allows accessing the root context (e.g. the values passed to the template engine scoped at the top of the file) through the variable `$`.
> chore(updatecli) simplify manifests using gotemplates by using root scope to get top-level values

- locals.tf
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2196274746
upgrading the publick8s kubernetes cluster and node pools to 1.28.9
> feat(publick8s): upgrade to kubernetes 1.28

- infra.ci.jenkins.io.tf
- publick8s.tf
- release.ci.jenkins.io.tf
- weekly.ci.jenkins.io.tf
- Use proper tags for resource groups
- Reword comment around disk permissions to give the real target (CSI driver, not the controller pods)
- Rename the publick8s static storage class to avoid confusion
- Update the shared tools to latest version
> cleanup: tune setup of AKS PV disks

- updatecli/updatecli.d/ci.sp.endate.yaml
- updatecli/updatecli.d/fs-sp-writer-end-dates_infra.ci.jenkins.io.tf.tpl
- updatecli/updatecli.d/fs-sp-writer-end-dates_trusted.ci.jenkins.io.tf.tpl
- updatecli/updatecli.d/infra.ci.sp.endate.yaml
- updatecli/updatecli.d/trusted.ci.sp.endate.yaml
This PR adds current end date to PR titles.
It also renames the templates as .tpl instead of .yaml, replaces "ExpiryDate" by "EndDate", ignores yamllint "line too long" rule, adds labels and lints the manifests.
> chore(updatecli): add current end date to PR titles

- test.ci.jenkins.io.tf
As per https://github.com/jenkins-infra/helpdesk/issues/4124
This PR allows me to create Azure VM ssh agents for maven17 and maven21 with my local vagrant controller (hence the public IP requirement)
> feat(test.ci.jenkins.io): Added permissions for Azure SP for public ips

- cert.ci.jenkins.io.tf
- ci.jenkins.io.tf
- dockerhub-mirror.tf
- infra.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4192
Fixup of https://github.com/jenkins-infra/azure/commit/91cf2dc8eb13120f20add9baddb1a44196f371bd
Reference Azure documentation: https://learn.microsoft.com/en-us/azure/container-registry/container-registry-artifact-cache?pivots=development-environment-azure-portal
This PR introduces an Azure Container Registry set up as a DockerHub mirror using a "Cache Rule" which mirrors `docker.io/*` to `*` (note: it forbids us to use other caching mechanism!).
This registry has the following properties:
- Only available in the "sponsorship" subscription
- Anonymous pull access (constraint due to Docker pull through cache - https://github.com/moby/moby/issues/30880)
- Private network only: since we have anonymous pull policy (see above), …
> feat(dockerhub-mirror) set up a new dedicated ACR to mirror DockerHub inside the Jenkins Azure infrastructure

- publick8s.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4206
This PR allows the cluster to fully manages IPs in this RG.
> fix(publick8s) allow cluster to manage network of public IPs

- .gitignore
- ci.jenkins.io-kubernetes-agents.tf
- ci.jenkins.io.tf
- outputs.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4204#issuecomment-2278334260
This PR introduces the following changes to allow ci.jenkins.io VM agents to access the private ACP in the `ci.jenkins.io-agents1` AKS cluster (instead of the azure.repo.jenkins.io ACP in the `publick8s` cluster):
- Allow the AKS cluster identity to manage Network on the whole Vnet (as per the Azure documentation - see comment)
- Required to create LB and NIC in both subnets. We could restrict a bit more but wouldn't protect us.
- Create private DNS records in the private DNS zone of the ci.jenkins.io vnet to point to thge internal ACP LB.
- Note: I moved the 2 existing DNS record close to this one. Only visual.
- Add NSG in/out rules in the ci.jenkibns.io ephemeral (VM- agents subnet to allow HTTP …
> feat(ci.jenkins.io) create resource to ensure an internal LB can be setup to reach ACP in the ci.jenkins.io-agents1 cluster

- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4240
This PR adds a new PVC statically provisioned based on an Azurefile to ensure a `ReadyMany*` access mode.
The goal is to have a centralized data dir. for the GeoIP database.
- Using a storage account reusable for the whole cluster, hence the naming. Type is Storage v2: means billing per request: only define file shares with low workload!
> feat(publick8s) add a persistent volume for maxmind/geoip

- privatek8s.tf
- publick8s.tf
While working on https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2294769030,
it appeared that we want the `publick8s` cluster to manage LB in the private data subnet of the **private** network as the private ingress is only expected to be accessed through the private VPN.
It also allows trusted.ci to access it (through the vnet peering trusted -> private).
> feat(publick8s) allow cluster to manage private data dtier subnet to allow creating internal LB

- locals.tf
As per https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2299149540:
Upgrading the infracijenkinsio_agents_1 kubernetes cluster and node pools to kub 1.28.9.
We can proceed to check the terraform plan
> feat(infracijioagents1): Upgrade cluster to kub 1.29.8

- locals.tf
Fixup of #806 
cc @jayfranco999 : we went a bit too quickly to set the version: `kubectl` (client side) is 1.29.8 which is the latest available 👍 
But the server side on AKS is not always the latest: Let's use https://github.com/Azure/AKS/releases in the future to validate prior to opening the PR ;)
> hotfix(infra.ci.jenkins.io-agents1) use a supported version of AKS

- outputs.tf
- public-redis.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4259
prepare a P2 instance for REDIS to use for both mirrorbits usage in publicK8S
Plan: 7 to add, 0 to change, 0 to destroy.
> feat(redis): add a public instance of redis for mirrorbits usage

- outputs.tf
- public-redis.tf
- updates.jenkins.io.tf
Cleanup old redis instance since #811 is in used by https://github.com/jenkins-infra/kubernetes-management/pull/5642
Related to https://github.com/jenkins-infra/helpdesk/issues/4259
> feat(mirrors.updates.jio): remove old redis and fmt

- updates.jenkins.io.tf
As these names are sensitive and should be managed in the same way as other publick8s records.
We initially set them here during the new Update Center experiment but the Update Center initial brownout (see https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2330934069) showed us that care is needed now that we promote these service to production grade.
- Terraform job is disabled: no checks
- Ran the following command to remove the elements from the state (as it's now managed in azure-net since <>):
```
terraform state rm azurerm_dns_cname_record.azure_updates_jenkins_io
terraform state rm azurerm_dns_cname_record.mirrors_updates_jenkins_io
```
- Note: we did not try using https://developer.hashicorp.com/terraform/language/resources/syntax#removing-resources as it's new to …
> hotfix(updates.jenkins.io) migrate CNAME DNS records to azure-net

- updatecli/updatecli.d/packer-resources-azurevm-end-dates.yaml
This PR tracks and updates the end-dates for the Azure credentials used by packer-resources.
This is required for the release of packer-images 2.0.0 since the build fails due to invalid ASP credentials.
(Related to https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2324132874)
> chore(updatecli):Track and update packer-resources AZ credentials end-dates

- updates.jenkins.io.tf
The hotfix commit https://github.com/jenkins-infra/azure/commit/62f7910ae5f53d398d4d9455cb32f8af73bb1e7e added a forgotten `import { }` block as a fixup #840.
It fixed the production but the staging is now failing due to this block (as there are NO Kubernetes namespace reachable in the staging).
This PR cleans up the code by removing the `import {}` which fixes the staging build
> chore(updates.jenkins.io) fix failing tests by cleaning up (already) imported resource

- outputs.tf
- updates.jenkins.io.tf
Fixup of #838 and #839
We need to keep some outputs. This PR either move them or add them back but in the `outputs.tf` file which is the Terraform convention.
Note: adding a comment explaining which script is using them.
> fix(outputs) ensure outputs required by trusted.ci.jenkins.io are defined

- outputs.tf
- trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
This PR adds a missing Azure SP to allow trusted.ci to write data into the new `redirects` UC file share and sets up outputs to ease the credential ZIP script generation.
> feat(updates.jenkins.io) add outputs and missing Azure SP to allow using new credentials

- publick8s.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4278#issuecomment-2328400184 and https://github.com/jenkins-infra/helpdesk/issues/4240
lets provide a write access for the kubernetes cronjob to update geoip-data
> feat(publick8s/geoip-data) provide a fileshare access for the cronjob

- outputs.tf
- trusted.ci.jenkins.io.tf
- updates.jenkins.io.tf
Since https://github.com/jenkins-infra/helm-charts/pull/1339, we can specify existing PVC for mirrorbits usage.
This PR defines statically provisioned (with the new typo-less storage class) volumes for the mirrorbits and geoip datas for (mirrors.)updates.jenkins.io.
It will allows us to have less setup and config in kubernetes management while keeping persistent volume under terraform control
> feat(updates.jenkins.io) define statically provisioned PVCs for mirrorbits data and geoipdata

- outputs.tf
- trusted.ci.jenkins.io.tf
- updatecli/values.yaml
- updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
This PR removes the (now) unused httpd file share and associated resources
> cleanup(updates.jenkins.io) remove deprecated httpd file share

- trusted.ci.jenkins.io.tf
- updates.jenkins.io.tf
The PR https://github.com/jenkins-infra/kubernetes-management/pull/5749 failed to deploy with the following error in the pod events (when CSI tried to mount the GeoIPdata volume):
```text
Please refer to http://aka.ms/filemounterror for possible causes and solutions for mount errors.
Warning  FailedMount  18s (x5 over 4m27s)  kubelet  MountVolume.MountDevice failed for volume "updates-jenkins-io-geoip-data" : rpc error: code = Internal desc = volume(updates-jenkins-io-geoip-data) mount //updatesjenkinsio.file.core.windows.net/geoip-data on /var/lib/kubelet/plugins/kubernetes.io/csi/file.csi.azure.com/0b6c3f7f2c0a4af88a040c48736703c5803f01808f4814df3d538ac17fc590c0/globalmount failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o …
```
> fix(updates.jenkins.io) fix the geoip data PV setup to use correct RG and node secret

- updatecli/values.yaml
Reverts jenkins-infra/azure#851
until we have problems with arm node pool for infra.ci agents
> Revert "New end date for `docs.jenkins.io` File Share service principal writer on `infra.ci.jenkins.io` (current: 2024-10-17T00:00:00Z)"

- updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4312#issuecomment-2429085702
This PR sets up custom mount options for the persistent volumes using SMB/CIFS fileshare, to limit side effects with the update of files "each 10 minutes" which may show files as present but empty.
- Default and recommended mount options are described in Azure documentation: https://learn.microsoft.com/en-us/azure/aks/azure-csi-files-storage-provision#mount-file-share-as-a-persistent-volume
- CIFS client options reference with explanations is there: https://manpages.debian.org/testing/cifs-utils/mount.cifs.8.en.html
NOTE: this change is not sufficient. Remount is required once deployed + Apache will need to be tuned.
> feat(updates.jenkins.io) specify custom mount options for the SMB/CIFS ROX PVs

- modules/private-resources/outputs.tf
- trusted.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4402#issuecomment-2506556409
The goal is to fix the error `ssh: connect to host updates.jenkins.io-data.trusted.ci.jenkins.io port 22: Connection timed out`
> fix(trusted.ci/ephemeral-agents) add NSG rules to allow access the PE

- outputs.tf
- updates.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
Both PVCs `updates-jenkins-io` and `updates-jenkins-io-redirects` are not used anymore.
Also adapting resource and outputs namings. Should resolve https://github.com/jenkins-infra/kubernetes-management/pull/5962 and https://github.com/jenkins-infra/kubernetes-management/pull/5969
> cleanup(publick8s + updates.jenkins.io) Removed unused SMB volumes and adapt PV/PVC namings

- infra.ci.jenkins.io.tf
following https://github.com/jenkins-infra/shared-tools/pull/164 and https://github.com/jenkins-infra/shared-tools/pull/160
allow infra.ci agents to connect through ssh to packer VM on aws
> fix(infra.ci) allow ephemeral agents to connect with ssh to internet (to allow packer on aws VMs)

- README.adoc
- mysql-public-db.tf
- postgres-public-db.tf
- providers.tf
- updates.jenkins.io.tf
Following work and discoveries by @smerle33 in https://github.com/jenkins-infra/docker-openvpn/pull/375 and https://github.com/jenkins-infra/docker-openvpn/pull/376
This PR corrects and documents the required accesses to allow us running `terraform plan` (before sending PRs) and `terraform apply` (hotfix/emergencies) from our admin machines.
- DBs routing is now fixed and using the VPN: documenting that `/etc/hosts` need to be updated (instead of using SSH tunnels) or using private subnets (infra.ci agents)
- Adding back the Update Center storage account IP restriction to the admin public IPs to avoid errors
> fix(db,updates.jio) correct and document network accesses to allow terraform from admin machines through VPN (instead of SSH tunnels)

- infra.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/packer-images/pull/1611#issuecomment-2552011686
This PR allows WinRM outbound to *any* internet IP, as we can't determine in advance the public IPs of packer images in EC2.
> feat(infra.ci.jenkins.io) allow WinRM from agents to anywhere

- infra.ci.jenkins.io.tf
- updatecli/updatecli.d/fs-sp-writer-end-dates_publick8s.tf.tpl
- updatecli/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4486
provide an updatecli manifest to track geoip expiration for the fileshare
(add a few corrections in docs and fmt)
> chore(updatecli): provide a manifest to track geoip fileshare enddates

- infra.ci.jenkins.io.tf
the SP for updatecli on azure has expired, this PR manually renew the SP.
nice to have an updatecli 
Plan: 2 to add, 0 to change, 1 to destroy. (1 add/1 destroy = report file)
```
-/+ resource "azuread_application_password" "updatecli_infra_ci_jenkins_io" {
~ end_date       = "2025-01-18T00:00:00Z" -> "2025-04-18T00:00:00Z" # forces replacement
```
> feat(infra.ci.jenkins.io) updatecli azure SP rotation

- updatecli/updatecli.d/updatecli-end-dates.yaml.tpl
- updatecli/values.yaml
add a manifest to track expiration date for the azure SP used by updatecli: https://github.com/jenkins-infra/azure/blob/254bf2f183987146fc6c5fd487cbda765ccc786d/infra.ci.jenkins.io.tf#L421
> chore(updatecli) track enddate for updatecli azure SP

- ci.jenkins.io-kubernetes-agents.tf
- infraci.jenkins.io-kubernetes-sponsored-agents.tf
- locals.tf
- outputs.tf
- privatek8s.tf
- publick8s.tf
This PR adds the hostname of the 2 "legacy" clusters (`publick8s` and `privatek8s`) to the infra report.
The goal is to allow Puppet and OpenVPN to access these information to keep the routing (to control planes through VPN).
> chore(outputs) export endpoints of publick8s and privatek8s

- ci.jenkins.io.tf
- imports.tf
- ldap.jenkins.io.tf
- outputs.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4544#issuecomment-2671068585
This PR sets up the LDAP backup Azure File volume to provide a statically provisioned PVC.
It uses the same technique as updates.jenkins.io's GeoIPdata volume which is the same kind (except LDAP backup are ReadWriteMany while GeoIpdata are ReadOnlyMany).
>  feat(ldap) provision statically the LDAP backup Azure File volume 

- ci.jenkins.io-kubernetes-agents.tf
- outputs.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4313#issuecomment-2675163487
This PR is a preliminary for #951 to avoid egg-and-chicken problems when removing both AKS cluster provider and its resources
> cleanup(cijenkinsio-agents-1) remove Kubernetes only resources as a first step

- outputs.tf
- privatek8s.tf
- publick8s.tf
- variables.tf
This change add data sources to retrieve the effective outbound IPs (v4 and v6 when present) so that we can export these IPs.
It also exports the Pod CIDRs for `publick8s` 
=> the goal is to allow LDAP LB source allow-list to be updated properly
> chore(output/publick8s/privatek8s)  export required outbound IP and CIDRs

- ci.jenkins.io-kubernetes-agents.tf
We want to avoid any credentials from the ci.jenkins.io controller
> hotfix(ci.jenkins.io-agent-1) do not create a kubernetes admin SA

- cijenkinsio-agents-1.tf
- locals.tf
Now that the network routing is fixed, we can proceed with the SA re-creation, so that infra.ci may manage the cluster.
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619#issuecomment-2769875877
> fix(cijenkinsio-agents-1) create the missing admin SA

- providers.tf
Fixup of #975 which did not reverted the changes on `providers.tf` from #951 .
That should allow the changes from #979 to pass
> hotfix(providers) uses the correct FQDN for the cluster cijenkinsio-agents-1

- cijenkinsio-agents-1.tf
- infraci.jenkins.io-kubernetes-sponsored-agents.tf
- locals.tf
- privatek8s.tf
- providers.tf
- publick8s.tf
As shown by hotfixes we had to apply (#978 #979) related to the cluster FQDNs in kubeconfigs,
this PR is a tentative to clean up all of these elements in the 4 AKS clusters:
- Removing unneeded outputs
- Ensure we have a sensitive output for each "kubernetes-management" kubeconfig for the infra.ci SOPS credentials. This should be the only "kubeconfig" output: if a maintainer is unable to retrieve the kubeconfig of a given AKS cluster for their machine, then they should not be granted maintainer permissions
- Fix the "kubernetes-management" kubeconfig to use the private FQDN (same as provider). Had to create a local for this as we cannot read the value from provider inside the kubernetes_sa module
- The local must be distinct from the current `aks_cluster` otherwise we have a cyclical …
> fix(AKS clusters) ensure we only outputs required management elements with the correct cluster hostnames

- ci.jenkins.io.tf
- cijenkinsio-agents-1.tf
- get.jenkins.io.tf
- locals.tf
- outputs.tf
- vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619
This PR creates the storage account with required network restrictions (hence adding the missing subnets), fileshare (premium SMB at 100 Gb), and the 3 couples of PV/PVC, along with the outputs
> feat(ci.jenkins.io/cijenkinsio-agents-1) create required storage and PV/PVCs for maven cacher

- ci.jenkins.io.tf
Fixup of #985 #987 and #988
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619
The failure to locate the azure file comes from a missing `provider` on the Azure File Share resource in the TF code.
The share has been created but cannot be read as it searches in a distinct subscription (Azure CDF instead of Azure Sponsored).
> hotfix(ci.jenkins.io) use correct provider for the `maven-cache` Azure File Share

- ci.jenkins.io.tf
- locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620#issuecomment-2778047717
> fix(ci.jenkins.io) correct SSH inbound rules to allow VPN routing through the public outbound interface

- ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620
Requires https://github.com/jenkins-infra/shared-tools/commit/f27614a0581a0c96284b86390c486720eec6b29e which disables non system identity Azure AD resource (AD App, SP and SP password).
> fix(ci.jenkins.io) move to system identity instead of distinct Azure AD SP

- ci.jenkins.io.tf
- outputs.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4620 and specifically https://github.com/jenkins-infra/helpdesk/issues/4628#issuecomment-2782788349
Requires the 2 following modules changes:
- Deprecates the boolean "use system identity" in favor of the presence/absence of the SP end date (absent on ci.jio, present on the other controllers): https://github.com/jenkins-infra/shared-tools/commit/925aa14b886b21f9db45b68ca47f621963b36f67
- Add more outputs: https://github.com/jenkins-infra/shared-tools/commit/4d27dbb98ff2af2ee07e7fef5ee89975a26a4060
> feat(ci.jenkins.io) improve workload identity setup and outputs

- cijenkinsio-agents-1.tf
ref. https://github.com/jenkins-infra/helpdesk/issues/4620
Otherwise BOM pods do not trigger the autoscaler because of label mismatch with pod template node selectors
> fix(cijenkinsio-agents-1) use the corect `role` label for the BOM node pool

- main.tf
- privatek8s-sponsorship.tf
Fixup of #997
- Use a new RG for public IP in the sponsored account. Ref. https://github.com/jenkins-infra/azure/pull/997/files#r2036991712.
- Use multiple but allowed zones for the system Node Pool. Ref. https://github.com/jenkins-infra/azure/pull/997/files#r2036989958.
> fixup(privatek8s-sponsorship) correct initial setup (zone for system pool and public IP RG)

- locals.tf
Ref. https://github.com/jenkins-infra/azure/pull/997/files#r2037035929.
As per https://learn.microsoft.com/en-us/azure/aks/concepts-network-azure-cni-overlay, the pod IPs are NAT-ed. So we can reuse the same CIDR on all clusters.
The constraint is to be sure that, at maximum node capacity, the CIDR can have a `/24` carved out for each node.
Since this sizing fits ci-jenkins-io-agents-1, we should not worry here.
> fixup(privatek8s-sponsorship) use the same private CIDR for pods as in other private clusters

- privatek8s-sponsorship.tf
Fixup of https://github.com/jenkins-infra/azure/pull/997
- chore(privatek8s-sponsorship) comment out Kubernetes resources until routing to private AKS API is set up - https://github.com/jenkins-infra/azure/pull/997/files#r2037520962
- fixup(privatek8s-sponsorship/linuxpool) fix error "The VM size of Standard_D4ads_v5 is only allowed in zones [2 1] in your subscription in location 'eastus2'. " - Ref. https://github.com/jenkins-infra/azure/pull/997/files#r2037501872
- fixup(privatek8s-sponsorship/infracictrl) fix error "OverconstrainedZonalAllocationRequest" - Ref. https://github.com/jenkins-infra/azure/pull/997/files#r2037512555
- fixup(privatek8s-sponsorship/releasepool) fix error "The VM size of Standard_D8ads_v5 is only allowed in zones [2 1] in your subscription in location 'eastus2'. …
> fixup(privatek8s-sponsorship) correct nodepools creation

- privatek8s-sponsorship.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2824642025
This change applies the same technique as for the provider. We have to use the DNS hostname (instead of the "privatelink" default hostname). Same as what we did for cijenkinsioagents1 and infraciagents1
> fix(privatek8s-sponsorship) correct hostname for AKS API to use internal DNS

- privatek8s-sponsorship.tf
(need to be Network Contributor on all subnets)
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2824642025
Required for the private Nginx ingress's LB
> fix(privatek8s-sponsorship) add missing 'Network Contributor' cluster permissions on subnbets

- infra.ci.jenkins.io.tf
- privatek8s-sponsorship.tf
- release.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2824642025
This PR defines the persistent volumes (and associated resources) in the privatek8s-sponsorship cluster for infra.ci.jenkins.io and release.ci.jenkins.io but in a statically define provisioning.
There are 2 cases:
- File shares (for release.ci agents in https://github.com/jenkins-infra/release/blob/c860d3c765aceefcc40e3a99f6f634ce944408d8/PodTemplates.d/package-linux.yaml#L35-L41):
- The PV/PVCs are Azure File Shares. They've been created in https://github.com/jenkins-infra/kubernetes-management/pull/6520, and they are now imported by this PR.
- Once merged: we'll have to revert https://github.com/jenkins-infra/kubernetes-management/pull/6520 AND we will be able to deprecate the helm chart …
> feat(privatek8s-sponsorship) add PV/PVCs for infra.ci and release.ci, including imported data

- release.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
This PR defines the most recent snapshot for release.ci to be imported into privatek8s-sponsorship cluster.
> feat(release.ci) migrate jenkins home data to privatek8s-controller

- archives.tf
- ci.jenkins.io.tf
- contributors.jenkins.io.tf
- custom-roles.tf
- docs.jenkins.io.tf
- get.jenkins.io.tf
- infra.ci.jenkins.io.tf
- javadoc.jenkins.io.tf
- jenkins.io.tf
- ldap.jenkins.io.tf
- plugins.jenkins.io.tf
- publick8s.tf
- stats.jenkins.io.tf
- updates.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
> fix(privatek8s-sponsorship) allow access to all resources already allowing the former privatek8s cluster

- custom-roles.tf
- privatek8s-sponsorship.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
- As per https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret, if we specify the secret through the `data` attribute, no need to base64 encode it. Fixup of #1020 
- Typo on the name of the role allowing infra.ci to read vnet for VM agents in thge new private-sponsored virtual network. Fixup of #1022
> hotfix(privatek8s-sponsorship) correct PV secret and custom roles typos

- custom-roles.tf
- infra.ci.jenkins.io.tf
- moved.tf
- privatek8s-sponsorship.tf
- release.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2839488075
This PR removes the data volumes not used anymore along with a bunch of unused infra.ci resources in the CDF subscription.
It also updates occurrences of old subnets with the new subnet (it should fix the failing VM agents on infra.ci)
> cleanup(infra.ci, release.ci) remove old privatek8s data volumes and migration data volumes along with old Entra permissions in old subscription

- cert.ci.jenkins.io.tf
- imports.tf
- moved.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4629#issuecomment-2846851326
As per https://go-acme.github.io/lego/dns/azuredns/index.html#azure-managed-identity-with-azure-workload, we can restrict permissions even further.
This is the goal of this PR, along with defining resources into a reusable module to avoid risks of copy and pasting when applying to trusted.ci.
Requires https://github.com/jenkins-infra/shared-tools/commit/4542811deb41dbb5ea0d146c01f0c588141232b5
> feat(cert.ci.jenkins.io) use a module for LetsEncrypt DNS setup: stricter authorization and reusability

- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-2855545179
Since https://github.com/jenkins-infra/kubernetes-management/pull/5398, there are no more applications running on this node pool: it's scaled to zero VMs:
> cleanup(publick8s) remove `x86small` node pool

- uplink.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4667#issuecomment-2894701228
The goal is to avoid accidentally removing/changing the schema and role during migrations.
> cleanup(uplink) temporarily stop managing the DB

- uplink.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4667#issuecomment-2894701228
This PR imports the runtime server (a pgsql flexible temp. instance with public access) to be used as runtime server and created through the wizard.
> feat(uplink) add a runtime server for the purpose of migration

- infra.ci.jenkins.io.tf
- privatek8s-sponsorship.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4651#issuecomment-2916842618
Requires https://github.com/jenkins-infra/shared-tools/commit/5021d7a28b66ef8ee77c3e8835f327c960de43c0 to ensure we can specify additional identities for permissions.
> feat(infra.ci.jenkins.io) enable workload identity and allow it to manage Azure VM agents

- infraci.jenkins.io-agents-2.tf
following  #1064 and #1063
max surge not available for spot instances
> fix(infraciagents2): remove maxsurge as it's not available for spot instances

- reports.jenkins.io.tf
Fixup of #1075 and #1074 
=> Azurefile CSI does not work and not needed with managed AKS as per https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/workload-identity-deploy-csi-driver.md#workload-identity-support
> workload identity is NOT supported on AKS managed Azure File CSI driver since the driver controller is managed by AKS control plane which is already using [managed identity](https://learn.microsoft.com/en-us/azure/aks/use-managed-identity) by default, it's not necessary to use workload identity for AKS managed Azure File CSI driver.
> fix(builds.reports.jio) add PVC and switch PVC to SAS token

- infraci.jenkins.io-agents-2.tf
- infraci.jenkins.io-kubernetes-sponsored-agents.tf
Useful for https://github.com/jenkins-infra/helpdesk/issues/4696, but also many other future use cases for using workload identities
> feat(infracijioagentsX) enable OIDC

- cert.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4696
Apply the same VM agents identity technique as #1079 but for cert.ci and trusted.ci.
> feat(cert.ci.jio/trusted.ci.jio) allow agents to write to builds.reports.jenkins.io

- mysql-public-db.tf
- postgres-public-db.tf
with https://github.com/jenkins-infra/helpdesk/issues/4689#issuecomment-2961894408
to avoid: 
```
Error: Error connecting to PostgreSQL server public-db.postgres.database.azure.com (scheme: postgres): dial tcp: lookup public-db.postgres.database.azure.com on 10.0.0.10:53: no such host
15:55:42  
15:55:42    with postgresql_role.keycloak,
15:55:42    on keycloak.jenkins.io.tf line 7, in resource "postgresql_role" "keycloak":
15:55:42     7: resource "postgresql_role" "keycloak" {
15:55:42  
15:55:42  
15:55:42  Error: failed to connect to MySQL: could not create new connection: could not connect to server: dial tcp: lookup public-db-mysql.mysql.database.azure.com on 10.0.0.10:53: no such host
15:55:42  
15:55:42    with mysql_database.matomo,
15:55:42    on matomo.jenkins.io.tf line 4, in …
```
> fix(public-dbs): vnet links with infracijioagents2

- infraci.jenkins.io-agents-2.tf
autoscaler seem to be a bit off with arm64 and nodepool starting at 0 ... as we use arm64 pods a lot, lets set it to 1 as min and check that the autoscaler works from here.
> feat(infracijioagents2): set minimum autoscaler to 1 for arm64 nodepool

- infra.ci.jenkins.io.tf
ref. https://github.com/jenkins-infra/helpdesk/issues/4696#issuecomment-3007450524
The Federated ID is currently in the sponsored subscription so let's start by removing it since it did not work.
We'll recreate a new one in a subsequent PR.
> cleanup(infra.ci) remove infraciagents federated identity used for testing

- ci.jenkins.io.tf
- infra.ci.jenkins.io.tf
- publick8s.tf
- trusted.ci.jenkins.io.tf
Fix warning messages such as:
```
│ Warning: Deprecated attribute
│ 
│   on infra.ci.jenkins.io.tf line 76, in module "infraci_contributorsjenkinsio_fileshare_serviceprincipal_writer":
│   76:   file_share_resource_manager_id = azurerm_storage_share.contributors_jenkins_io.resource_manager_id
│ 
│ The attribute "resource_manager_id" is deprecated. Refer to the provider documentation for details.
│ 
│ (and 6 more similar warnings elsewhere)
```
Requires https://github.com/jenkins-infra/shared-tools/commit/f847ce3da16ae12da0660bc8bae20bbeb1838e60
> chore: fix warning messages about depreciated 'resource_manager_id' attribute

- ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4688
> cleanup(ci.jenkins.io) stop managing ci.jio CNAME records (moving to azure-net)

- privatek8s-sponsorship.tf
- release.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4696#issuecomment-3008168249
lets set the necessary objects for workload identity, as per jenkins-infra-ci controller.
> feat(privatek8s/release.ci-agents): add credential-less workload identity for release agents

- vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4688
Fixup of #1099
> cleanup(vnets) remove remnants of azure.ci in the sponsored subscription

- outputs.tf
- trusted.ci.jenkins.io.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4694
Follows up #1107 (and its hotfix)
> feat(trusted.ci) ensure ephemeral agentsin the CDF account uses default values and are outputed

- infra.ci.jenkins.io.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4701
following: https://github.com/jenkins-infra/azure/pull/1113
fixup with both network ips in the destination prefixes AND a manual remove of the ressources group and gallery that remained from previous migration
> fix(packer-images): correct the NSG with both sponsorship and CDF subscription

- infra.ci.jenkins.io-agents-sponsored.tf
- infra.ci.jenkins.io.tf
- locals.tf
- outputs.tf
- vnets.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4692 and https://github.com/jenkins-infra/helpdesk/issues/4690
- A file is created to only hosts sponsored subscription resources (easier to delete later)
- outputs and locals related to infra.ci moved to the correct source files
- Resources for infra.ci (both controller for https://github.com/jenkins-infra/helpdesk/issues/4690 and agents for https://github.com/jenkins-infra/helpdesk/issues/4692) created
- Note: No Azure SP created. We'll try to work credential-less from the beginning.
> feat(infra.ci.jenkins.io) split resources per file per subscrption and create CDF resources for infra.ci (controller and agents)

- infra.ci.jenkins.io-agents-sponsored.tf
- infra.ci.jenkins.io.tf
- infraci.jenkins.io-agents-2.tf
- outputs.tf
- privatek8s-sponsorship.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4692
See https://github.com/jenkins-infra/azure/pull/1118#issuecomment-3112773659
- Fix the infra.ci agents storage account naming to avoid collisions
- Update outputs (add missing elements and switch report to infra.ci CDF agents setup)
- NSG rules failed to create with `Rules cannot have the same Priority and Direction` have been manually removed so replacement will happen once this PR is merged
- Role Definition `azurerm_role_definition.infra_ci_jenkins_io_controller_disk_reader` not created due to `RoleDefinitionWithSameNameExists: A custom role with the same name already` error:  typo fixed (removing the "sponsoring" string in the name
- Remove the (currently unused) UAID `infra_ci_jenkins_io` from the sponsored subscrption …
> fix(infra.ci.jenkins.io) fixup of #1118 (many errors)

- dockerhub-mirror.tf
- infra.ci.jenkins.io.tf
Fixup of #1130 where I copy-and-pasted from infra.ci which utilizes a distinct Azure Principal to access keyvault.
> fix(dockerhub-mirror) correct invalid access-policy (wrong principal ID)

- outputs.tf
- privatek8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4690
Note: Successfully applied manually (due to infra.ci being down - https://status.jenkins.io/issues/2025-07-29-infra.ci-down/) 
```
Plan: 9 to add, 2 to change, 8 to destroy.
```
> fix(privatek8s) use meaningful naming for infra.ci and release.ci PV/PVC/NS

- archives.tf
- builds.reports.jenkins.io.tf
- contributors.jenkins.io.tf
- docs.jenkins.io.tf
- get.jenkins.io.tf
- javadoc.jenkins.io.tf
- jenkins.io.tf
- ldap.jenkins.io.tf
- locals.tf
- main.tf
- outputs.tf
- plugins.jenkins.io.tf
- publick8s.tf
- puppet.jenkins.io.tf
- stats.jenkins.io.tf
- trusted.ci.jenkins.io.tf
- updatecli/updatecli.d/service-ips.yaml
- updates.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4765
Note: by stopping the usage of the terraform module, we are switching to an updatecli "automated updates" pattern instead.
A few important changes:
- Admin public IPs are migrated to `local` and also exported to the report (to migrate them on other projects)
- No more public admin IP allowed for storage accounts
- trusted.ci.jenkins.io: using the `pkg.origin.jenkins.io` naming instead of `updates.jenkins.io` since we migrated the Update Center a few months ago
----
Updatecli check is expected to fail (diff on a remote, not local branch) but was tested locally with success by commenting out the target's `scmid` attributes
> cleanup: remove leftovers of the decommissioned Azure sponsored subscription and the shared terraform 'infra' module

- data-storage-jenkins-io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4767#issuecomment-3180139293
- Same setup as the current updates.jenkins.io storage
- 750 Gb provisioned
- Already create NS and secret for the PV in `publick8s`
> feat(data.storage.jenkins.io): create NFSv4-ready centralized premium storage

- outputs.tf
- privatek8s.tf
- release.ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4767
In order to work with the future get.jenkins.io [with mirrorbits v0.6.0](https://github.com/jenkins-infra/helpdesk/issues/4764) and [NFS file system](https://github.com/jenkins-infra/helpdesk/issues/4767#issuecomment-3180139293), we need a PVC in `privatek8s`'s namespace where the [release.ci.jenkins.io Linux packaging agents](https://github.com/jenkins-infra/release/blob/master/PodTemplates.d/package-linux.yaml) are launched.
This is the goal of this PR.
Note: it also moves the set of PV/PVCs currently used into release.ci scope (easier to track and to cleanup once the move will be done)
> feat(release.ci.jenkins.io/privatek8s) create data-storage NFS PV/PVS for packaging agents

- cert.ci.jenkins.io.tf
- dockerhub-mirror.tf
- infra.ci.jenkins.io.tf
- trusted.ci.jenkins.io.tf
Fixup of https://github.com/jenkins-infra/azure/pull/1171#issuecomment-3199486226
Note: terratest are annoying here as they show the weakness of terraform plan on an empty platform when a lot of "dynamic" loops are used. As such, we do not "add" some resources when running in terratest to avoid errors.
This PR also adds NSG rules for trusted <-> ACR (missing in #1171)
> fix(dockerhub-mirror) use existing private DNS zone for trusted.ci 

- locals.tf
- old_publick8s.tf
- privatek8s.tf
- publick8s.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4617#issuecomment-3295780800
New attempt as #1187 failed and was roll backed in #1188 with the following changes:
- ~Use AzureLinux3 as per Azure's depreciation email~ (Failed to specify `AzureLinux3` - https://github.com/hashicorp/terraform-provider-azurerm/issues/30575 so we stick with the default)
- Set up the cluster's default egress method to a load balancer with same settings as before: IPv6 requires the LB as [NAT gateway do not support IPv6](https://learn.microsoft.com/en-us/azure/nat-gateway/faq#can-an-ipv6-public-ip-address-be-used-with-a-nat-gateway).
- Ipv4 also goes through the LB as it is the *main* egress method. IF the LB fails, then NAT gateway will be used (and IPv6 will fail)
> feat(publick8s) create a new cluster with modern (2025) setup

- dockerhub-mirror.tf
- infra.ci.jenkins.io.tf
- javadoc.jenkins.io.tf
- providers.tf
- publick8s.tf
- release.ci.jenkins.io.tf
Cleaning up things discovered along the way while working on #1187 #1188 #1190 and #1191.
No resources changes expected: it is only Terraform code cleanup (deleting `moved` block` already applied, removing unused provider, fixing `azurerm` provider depreciation messages
> cleanup: fix depreciation messages and remove unused directives

- locals.tf
- reports.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4617
- Add PV/PVCs (and NS + secrets) in CSI to existing web services shared accounts
- Create a new file share for reports.jenkins.io (start empty)
Note: all these PV/PVCs are expected to move (soon) to the centralized NFS: https://github.com/jenkins-infra/helpdesk/issues/4767. For now, let's migrate web services to the new cluster with explicit PV/PVCs (instead of pod direct CSI mounts in the old `publick8s-endless-ghoul` cluster)
> feat(publick8s) add custom PV/PVCs for all web services except www

- ldap.jenkins.io.tf
- locals.tf
- old_publick8s.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4617
Same as https://github.com/jenkins-infra/azure/pull/1203 but for LDAP with:
- New RG, storage account, file share and disk with proper naming convention
- Storages are empty and will need to be populated twice (once for initial filling, second at migration time)
- Will need a subsequent PR for renaming thing (will be a chore) once resources are created
> feat(ldap-jenkins-io) create new RG and storages with proper naming convention

- locals.tf
> cleanup(locals) removed old references from publick8s-endless-ghoul cluster

- locals.tf
Following https://github.com/jenkins-infra/helpdesk/issues/4617
This PR bumps the `publick8s` cluster version (patch only) as a preliminary to https://github.com/jenkins-infra/helpdesk/issues/4817 with 2 goals:
- Ensure that the cluster is good (after the unexpected outage described in https://github.com/jenkins-infra/helpdesk/issues/4813 which we don't want to reproduce)
- Ensure that we'll have the same (latest) Kubernetes 1.32.x available version with the new other clusters to be upgraded
----
Expected change: all nodes will be re-created. Expecting a LDAP restart
> chore(publick8s) bump patch version of AKS (1.32.6 -> 1.32.7)

- locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4817
Already applied manually: PR is only there for tracking.
> feat(infraciagents-agents-2) bump AKS from 1.31.6 to 1.32.7

- outputs.tf
- reports.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4821#issuecomment-3372038800
We forgot to allow trusted.ci agents for reports storage
> fix(reports) allow access from trusted.ci agents
